### ISSUE TITLE
Error parsing numbered bullet in Markdown

### ISSUE THREAD

**Issue by bulrush15** [markdown-it/markdown-it#1019]
I'm using Tiddlywiki 5.3.3 on Brave Browser on Windows 11. 

I checked the dingus and this is a bug. The problem does not happen in the dingus, just in this TW plugin. 

When I type in this markdown in Tiddlywiki 5.3.3: 

```
1. 2012. Research reveals women are more interested in a man’s earning capacity than the size of his wallet. 
```

I get this incorrect result of digits overlapping. 
![image](https://github.com/markdown-it/markdown-it/assets/7031486/9e71f39f-872b-4a14-8ce5-fc60bdcb869b)

However this does not give me the overlapping text. 

```
2. 2022-0420. On Internet Dating Sites, Women Prefer Men With Higher Incomes and More Education
```

**Comment by puzrin** [comment]
I see exactly the same HTML result in dingus and markdown-it

- https://spec.commonmark.org/dingus/?text=1.%202012.%20Research%20reveals%20women%20are%20more%20interested%20in%20a%20man%E2%80%99s%20earning%20capacity%20than%20the%20size%20of%20his%20wallet.%20%0A
- https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%202012.%20Research%20reveals%20women%20are%20more%20interested%20in%20a%20man%E2%80%99s%20earning%20capacity%20than%20the%20size%20of%20his%20wallet.%20%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

You need to escape second dot to avoid nested sub-list. Looks like spec use related question, not about this package.

If I missed something - add more details. Please use demo links instead of screenshots and so on. That simplifies understanding of your case.
