### ISSUE TITLE
Regression with v14.1.0 regarding ~~strikethrough text~~

### ISSUE THREAD

**Issue by Lucas-C** [markdown-it/markdown-it#1024]
Hi

Thank you for maintining `markdown-it`!

I discovered a minor regression with the latest published version:
```
$ node -v
v18.19.1

$ npm i markdown-it@14.0.0

$ node -e 'console.log(require("markdown-it")().render("~~⚀~~one"))'
<p><s>⚀</s>one</p>

$ npm i markdown-it@14.1.0

$ node -e 'console.log(require("markdown-it")().render("~~⚀~~one"))'
<p>~~⚀~~one</p>
```

This bug only appears when using non-ASCII characters: it won't happen if `⚀` is replaced by `1` in the sample code above.

**Comment by rlidwka** [comment]
This is so much easier to test different versions with:

```
$ echo "import md from 'npm:markdown-it@14.1.0'; console.log(md().render('~~⚀~~one'));" | deno run -
```

Thanks for the report. But I think that it is not a bug, but intentional change in the spec: https://github.com/markdown-it/markdown-it/pull/1009 (see point 3)

`⚀` is Other Symbol (`So`), and the entire `S` class is now treated as punctuation which it wasn't before (so now behavior is the same as with `~~&~~one` for example).

**Comment by Lucas-C** [comment]
Thank you for the explanation @rlidwka

This was annoying in my case, as it "broke" some PDF rendering that was based on `~~⚀~~` strings being converted to `<s>` HTML tags.

I'll find a workaround.
AFAIC, no problem to treat this as a non-bug.

**Comment by puzrin** [comment]
@Lucas-C markdown does not allow express "anything user can imagine without restrictions". Sometimes shit happens :). Our point is - "You can tweak the parser to non-standard behavior, but we don't respond for that." IMHO, if you need old behaviour for `~~`, it should be possible to pick old code, and substitute default `~~` rule.
