### ISSUE TITLE
Proposal: use JsonML as an intermediate representation

### ISSUE THREAD

**Issue by alexkuz** [markdown-it/markdown-it#105]
My little project [**Markdown React**](http://alexkuz.github.io/markdown-react-js/) now uses your library as markdown parser instead of [**markdown-js**](https://github.com/evilstreak/markdown-js/). **MarkdownIt** seems to me much more flexible and powerful; however, **markdown-js** has one advantage, which is crucial for me: it provides AST in JsonML format, which is quite easy converts to React components. It's not a big problem for library itself (for which I wrote simple converter to JsonML), but it's hard to support any plugins, as they render to plain HTML.

I guess it would be a significant change in API and frankly I don't know if there are any other usecases, but anyway, it's worth a try :)

**Comment by puzrin** [comment]
Sorry, no such plans. It was intentional decision to keep things simple - no ast and no exact sourcemap. I understand that some things can be done different/better, but i'm ok with current result. If someone wish to do one more rewrite or create another parser - i'll try to help, but don't plan to spend significant time for it.
