### ISSUE TITLE
Lazy continuation of tables inside block quotes

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#114]
GitHub doesn't stop table at the first not quoted line. In the following example

```
> foo|foo
> ---|---
> bar|bar
baz|baz
```

`baz|baz` becomes the next row of the table inside the block quote.

Markdown-It makes this line a paragraph following the block quote.

**Comment by rlidwka** [comment]
In the CommonMark, lazy continuation is defined only for paragraphs. For example, if you replace a table with a fence, the fence will terminate right after last `>`:

    > ```
    > this is a part of the fence
    this is not
    ```

Github parses this differently than the CommonMark standard tells you to, and since we are following CommonMark spec, Github compatibility isn't an option here.

-----

That was the general reason why it works like that. However, we could make an exception specifically for tables. Should we?

There is no specification for tables. And as far as I see, github support for them is weird. For example, they cannot be nested in lists:


```
- foo|foo
  ---|---
  bar|bar
  baz|baz
```


- foo|foo
  ---|---
  bar|bar
  baz|baz

`markdown-it` should handle it as a table inside a list. Also, in this case with blockquotes laziness doesn't work even in the gfm:

```
> foo|foo
---|---
bar|bar
baz|baz
```

> foo|foo
---|---
bar|bar
baz|baz

Based on this, I would say `markdown-it` implementation is actually better (as in "more consistent"). Maybe file a bug against Github parser to follow CommonMark? :)

**Comment by puzrin** [comment]
@opennota let us know if this issue is critical for you. For now i think it's better to leave things as is until clear spec for the tables ome to commonmark.
