### ISSUE TITLE
parseInline doesn't parse ```syntax

### ISSUE THREAD

**Issue by reggi** [markdown-it/markdown-it#146]
The line below is parsed different for `parse` and `parseInline`

    ```js
    var foo = 'bar'
    ```

```
[
  {
    "type": "fence",
    "tag": "code",
    "attrs": null,
    "map": [
      0,
      3
    ],
    "nesting": 0,
    "level": 0,
    "children": null,
    "content": "var foo = 'foo'\n",
    "markup": "```",
    "info": "js",
    "meta": null,
    "block": true,
    "hidden": false
  }
]
```

vs

```
[
  {
    "type": "inline",
    "tag": "",
    "attrs": null,
    "map": [
      0,
      1
    ],
    "nesting": 0,
    "level": 0,
    "children": [
      {
        "type": "code_inline",
        "tag": "code",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "js var foo = 'foo'",
        "markup": "```",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      },
      {
        "type": "softbreak",
        "tag": "br",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      }
    ],
    "content": "```js\nvar foo = 'foo'\n```\n",
    "markup": "",
    "info": "",
    "meta": null,
    "block": false,
    "hidden": false
  }
]
```

with no syntax support

**Comment by vyp** [comment]
Well yes, isn't this just expected? A fenced code block is a leaf block, not an inline.

**Comment by reggi** [comment]
@vyp within the `content` for a block using `parseInline` it contains `js var foo = 'foo'` that `js` string is from the syntax declaration. This is parsed correctly with `parse()` and unexpectedly with `parseInline()`.

**Comment by vyp** [comment]
@reggi What I mean is, inline does not have any idea of 'blocks', so it just parses everything like they would be inline. So with parseInline, I would expect the contents of the child to be `js var foo = 'foo'`, with surrounding markup of three backticks.

Also, I think it's a typo at the start where you say `var foo = 'bar'`, I think it should be `var foo = 'foo'`, which is what the json says.

**Comment by reggi** [comment]
@vyp Thanks for the explanation.

I really still don't get the significance of why specifying `inline` makes a difference how the parser interprets code tags (ticks, blocks, whatever you want to call them) with or without syntax highlighting defined. The default for `parse()` is to accommodate the `info` portion of the ticks, and the default for `parseInline()` is to not accommodate the `info` portion of the ticks. What does this seemingly arbitrary decision have anything to do with it being inline or not?

Anyway, sorry if I'm coming off as crass, I really just thought this was a bug, and I'm trying to help. If It's not, I just want to understand why.

**Comment by vyp** [comment]
> I really still don't get the significance of why specifying inline makes a difference how the parser interprets code tags [...]

It's because fenced code blocks (i.e. blocks of code surround by three backticks) are what the spec says are "blocks". And basically a markdown document is defined as a sequence of blocks: http://spec.commonmark.org/0.21/#blocks-and-inlines

As that link says, some blocks can contain other blocks, and some can contain "inlines". So for example a paragraph is block that can contain inlines such as emphasised text (text surrounded by asterisks).

So when you're using `parseInline`, I'm assuming because markdown-it is a commonmark compliant parser, this function parses only the "inlines" under here: http://spec.commonmark.org/0.21/#inlines

As you can see, there's no such thing as a fenced code block in this section. However, there is something called a ["code span"](http://spec.commonmark.org/0.21/#code-spans), which is just code surrounded by single backticks. But, as you can see, these have no concept of an "info string" like a fenced code block does: http://spec.commonmark.org/0.21/#fenced-code-blocks.

So I think [example 297](http://spec.commonmark.org/0.21/#example-297) demonstrates most closely why `parseInline` works the way it does. It says "Line endings are treated like spaces" just above it.

So when you're saying to parse:

    ```js
    var foo = 'bar'
    ```

using `parseInline`, you're telling it to parse it basically as the *contents of a block*. So what I'm assuming happens is that the parser takes everything between the third and fourth backticks as an inline "code span" element, and because line endings are treated like spaces, that's why we see a space between `js` and `var` in the `js var foo = 'bar'` result.

> Anyway, sorry if I'm coming off as crass, I really just thought this was a bug, and I'm trying to help. If It's not, I just want to understand why.

That's okay. :)
I'm not an official developer of this project or anything, so I'm just unofficially trying to help too, but that also means I may be wrong.

**Comment by puzrin** [comment]
parseInline = parse inline tags only. See source code.

**Comment by reggi** [comment]
@vyp WOW THANK YOU SO MUCH FOR YOUR TIME :) :rainbow: :rabbit: :+1: :smiley: :hamburger: :100:

**Comment by vyp** [comment]
@reggi Sorry if I offended you, that wasn't my intention.
