### ISSUE TITLE
Minibuild

### ISSUE THREAD

**Issue by IngwiePhoenix** [markdown-it/markdown-it#173]
Hey.

I have a prototype of a tiny syntax-highlighting editor. It uses [LDT](https://github.com/kueblc/LDT) and [behave.js](https://github.com/jakiestfu/Behave.js).

So far, I have used regexes to parse markdown. But as you can tell, you can't quite cheat like that :) So I wanted to use the same markdown parser that I use server-side.

However, bluntly require'ing the module results in a 99kb big file (uglified). That...is big. Considering that I am not even really rendering or something at all - that is a bit too much. So I wanted to ask: How can I archieve the smallest build?

I want:
- To parse the markdown the user is typing.
- Get an AST-kinda-thing which I can tweak and pass to LDT to generate the proper highlighting.

Any idea? :)

You can see my current prototype here: https://github.com/DragonsInn/BIRD3/blob/yii1_to_laravel5/app/Extensions/Editor/MarkdownEditor.oj (written using [OJ](https://github.com/musictheory/oj)).

Kind regards,
Ingwie.

**Comment by puzrin** [comment]
1. In short - no. You can't decrease size a lot. But it's better to compare gzipped + minified size, not just minified.
2. In wide:
  - Many places can be rewritten if speed is not critical. To use regexes instead of charcodes check.
  - big entities table can be replaced with encode/decode via browser's DOM. That will cause some difference on edge cases, but... nobody cares.
  - if you don't need autolinking, linkifier can be dropped, and some unicode

My opinion is:

- that will became a separate project, and will require s separate maintenance
- even if miracle happen and gzipped size will be reduced from 35K to 20K, that's will not compensate time been spent.

You also can dig #6.

**Comment by IngwiePhoenix** [comment]
I went with just including the whole bundle and making sure the remaining package isnt too big. Looks like its all I can do, for now.

Thanks for your insights. :)
