### ISSUE TITLE
Question: Best way to add additional custom classes and HTML to markdown processing

### ISSUE THREAD

**Issue by ScopiCisco** [markdown-it/markdown-it#174]
Hello Team,

I am trying to provide the ability to have the additional markdown you see in JIRA for adding "color" to inline text.  I have tried to scour the plugins and the markdown-it code.  I don't believe I have found an existing plugin that satisfies what I need.  

Let me say I really like how this was written and the direction it is going.  The plugin/override model I believe is the power of this library.

My input that I am trying to have is

"The following value {color:red}42{color} is incorrect."

I would like to render this as 

&lt;span&gt;The following value &lt;/span&gt;&lt;span class="text-danger"&gt;42&lt;/span&gt;&lt;span&gt; is incorrect&lt;/span&gt;

There is the plugin markdown-it-attrs, but it assumes the closing } is at the end of a token or text block.

So I see this problem broken down into two items

1.  Custom render for text tokens to possibly wrap in a span element
2.  Wrapping text with span and custom class for supported colors.  (Our system is limiting the supported colors at this time to reduce choices)

Now to my questions.

1.  Would it be best to have a plugin detect the {color:red} .... {color} section, create a text token and add the color, red pair as an attribute?
1b.  Then have custom renderer for text tokens to pull the attributes out and add appropriate classes and also wrap text in span?
1c.  Also I am thinking the plug in would be placed in the inline.ruler after 'emphasis' similar to -sub and -sup plugins.

2.  Create a custom token with a tag of span and add the attributes to the token and only render the containing text with a span?

I have been looking at -sub, -sup, -attr for direction and also stepping into the markdown-it source to see how it works.

I am inclined to go with number 1 as {color:red} is really just an attribute on the following text.

Thoughts?

I would to create the general plugin for this and put it back out for the community, maybe somthing like

markdown-it-text-color?

Thanks,
Scott Saltsgaver
Cisco Engineer

**Comment by puzrin** [comment]
I think, the best way to add new markup is via new tokens (if it's technically possible). If you can keep extension logic & data completely isolated - do it.

Personally, i'd warn against using `{}` markup, because it conflicting with maruku-like extensions and can conflict with future CM spec (because it will include something similar). But it you don't need compatibility - that on your own. Initially, we did this parser because we needed not compatible extensions :) .

> `<span>The following value </span><span class="text-danger">42</span><span> is incorrect</span>`

I think more correct will be `The following value <span class="text-danger">42</span> is incorrect`. At least, if you don't have special requirements to have dummy spans.

In general:

- I see no technical problems to add new "pair" via plugin.
- If your markup is not final, probably digging topics in http://talk.commonmark.org/ will give you a lot of ideas.
- We do not reserve names for our own use. Use anything you wish. Also i stay, that plugin developpers should not depend on mainstream and opinion of core devs :) . If you will see, that existing API limits you somehow - feel free to post your proposals.

**Comment by ScopiCisco** [comment]
Hello Vitaly,

So I did do some digging over in commonmark, but as you know with all search engines, may not have picked the correct search terms :-)

Your points were spot on and agree with them.  Let me expand on what we are doing and some of my goals, but I believe the answer will be create the plugin, and have others comment on it.

I am putting together a general web page that exposes a tooling system we have in house.  This tool system allows engineers to write scripts in many languages and the scripts receive input, parse it and present output.  If my web page was the final web page for all the scripts, then yeah I could just use inline spans and css.  But, there are three to four known means of accessing these scripts and their output.  It is very difficult to have every system use the same HTML/CSS and also as CSS evolves to go back and update the scripts to the new CSS is near impossible.  

So we were looking to dumb down the output language so that the front end takes care of the HTML generation.  Markdown provides that perfect tool in that you get a general language that hasn't changed much around the basics to add styling and possibly with extensions for other text attributes to not have to touch the scripts again.

So you "warned" against using curly braces.  Do you see a more appropriate delimiter?  Was also afraid that using {} would conflict with -attr plugin as well.  My fear is any delimiter will have the possibility to interfere :-).  

Also -attr supports the {.<class>} but again I am propagating view semantics to the parsing engines.

So I am trying to possibly create a general plugin, not pollute backend scripts with view semantics and also possibly not conflict with future Markdown or existing plugins.

Another approach would be to modify -attr plugin to support its existing rules (last character in block must be a }) to also support multiple inline.  Then it could be an option of which way to use.  But I think that may make the plugin more confusing as well.

But from reading and rereading and searching I may just need to create the plugin and then we will see what the community says.  Willing to update and correct issues and hope that others find it useful.  

I very much appreciate the quick and thorough response, I tried to follow your direction before and do due diligence prior to writing.  Keep up the good work, really do like this module.

**Comment by puzrin** [comment]
I think your task can be splitted to 2 phases:

1. Define wished markdown markup and wished presentation ouput.
2. Investigate optimal implementation.

(2) is almost useless until you know exactly (1). And for (1) commonmark forum is much better place. I stay aside of any spec-related talks, because it's a very big question, completely separated from implementation (this project, or reference one). Also, guys at commonmark forum are more competent than me in this area.

**Comment by ScopiCisco** [comment]
Will post a question over there soon.  

Thanks again.

**Comment by puzrin** [comment]
Closing?

**Comment by ScopiCisco** [comment]
Yes sir.
