### ISSUE TITLE
Emedding links

### ISSUE THREAD

**Issue by sergeyt** [markdown-it/markdown-it#192]
I wrote [this embed](https://github.com/reactbits/markdown/blob/master/src/embed.js#L106) plugin. Are there other easy ways to customize rendering of links without writing lexer/parser extension? Maybe this is feature request for linkify or even markdown-it core.

**Comment by puzrin** [comment]
You can manipulate tokens before renderer https://github.com/markdown-it/markdown-it-for-inline#use or write 2-stage parser (markdown -> html -> html AST -> anything else). Also you can descrive videos as image instead of link. We use 2-stage parser in nodeca, because we have too complicated processing.

**Comment by sergeyt** [comment]
@puzrin thanks for answer!
