### ISSUE TITLE
Incorrect claim in repo header

### ISSUE THREAD

**Issue by nikolas** [markdown-it/markdown-it#194]
As Alex mentioned here: https://github.com/markdown-it/markdown-it/pull/186#issuecomment-172041448, markdown-it isn't 100% compatible with the CommonMark spec, yet this repository's description claims:

> Markdown parser, done right. 100% CommonMark support, extensions, syntax plugins & high speed

I think it would be good to change "100%" to a more accurate calculation of how far markdown-it deviates from the commonmark spec. That way, people can know it needs work and can help out. Just an idea.

**Comment by puzrin** [comment]
@nikolas you did not understood him right. Markdown it is 100% compatible. But test files must be updated properly.

**Comment by rlidwka** [comment]
The goal of this project is 100% compatibility with CommonMark spec (and no changes that break compatibility are accepted).

**And hey, we did it!** The current release (that's markdown@5.0.2) is 100% compatible with CommonMark 0.22, which could be checked if you look at this [list of failing tests](https://github.com/markdown-it/markdown-it/blob/378ac9074e393354253281fbe243860732d1f631/test/fixtures/commonmark/bad.txt) (and a history of that file).

Of course, CommonMark spec is a moving target, and we can't comply with newest releases right away (it takes time to implement it). So as of now, 12 out of 613 tests fail on CommonMark 0.24, though this amount is expected to be shrinking close to zero next week.

Since most of the releases do have 100% compatibility with a reasonably recent CM specification, I think this statement is acceptable. There just isn't enough space for lawyer-speak in the project title.
