### ISSUE TITLE
Markdown to Textile or another markup

### ISSUE THREAD

**Issue by kpym** [markdown-it/markdown-it#196]
I'm looking for javascript transpiler between markup languages and I can't find one.
I came to see that markdown-it rules can be customized. 

**So is it possible for example to fully customize them in a way to produce textile output in place of HTML?**

If yes, could you give me an example how we can customize the header rule that will transpile : 

~~~~~~~
# Title
~~~~~~~

to 

~~~~~~~
h1. Title
~~~~~~~

**Comment by puzrin** [comment]
Writing and reading are completely different tasks. This project is about "reading". Don't be confused, that it can produce HTML.

You can use [parse](https://markdown-it.github.io/markdown-it/#MarkdownIt.parse) method to get tokens, then process those as you need. For example: parse -> tokens -> your AST -> your format. Existing renderer is for HTML and will be no much use for other things.

**Comment by kpym** [comment]
So if I understand you : "You can add new rules and even replace existing ones." concerne only "read" rules ?

So to produce another markup from textile I have to rewrite the `MarkdownIt.render`  method ?

**Comment by vyp** [comment]
> I'm looking for javascript transpiler between markup languages and I can't find one.

Maybe it's possible to render to textile instead of html with markdown-it, but maybe you should also try to use pandoc on ghcjs: <https://github.com/osener/markup.rocks>. The live demo is at <http://markup.rocks/>. If you click that link, once it loads, click the "Preview" dropdown menu on the right, and then click "Textile" from those options. Then you can see that the markdown on the left has been converted to the textile representation on the right. Note that this conversion is done client side (with javascript).

Then you may want to contact the author of that project for the details on how to use it yourself and work with it. Hope that helps.

**Comment by kpym** [comment]
@vyp Thanks for the advise but this is a 2.2Mb monster library. I think that converting between markdown ans textile should be not so hard :stuck_out_tongue_winking_eye:.

**Comment by puzrin** [comment]
> So to produce another markup from textile I have to rewrite the MarkdownIt.render method ?

Yes. And since you need full rewrite, you can call `.parse()` directly as i suggested. I would recommend to search markdown/textile writers packages first, may be someone did it.

PS. Advice about pandoc is good.

**Comment by vyp** [comment]
@kpym Well it is pandoc on ghcjs! :p And it's not just markdown -> textile, it can convert between a lot of other various markup formats. But yes, 2.2 MB is huge, you're right. :/
