### ISSUE TITLE
Feature request: table footer

### ISSUE THREAD

**Issue by unindented** [markdown-it/markdown-it#23]
You already support table headers (`<thead>`) but it'd be nice to be able to add table footers too (`<tfoot>`).

Kramdown supports them: http://kramdown.gettalong.org/syntax.html#tables

Maybe something along those lines?

```md
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
============= | =============
First Footer  | Second Footer
```

**Comment by puzrin** [comment]
Tables support is currently minimalistic and limited with GH syntax. Since we don't like to establish "new standard", it's better to postpone changes untill tables syntax added to [CommonMark](http://commonmark.org/) spec.

But nobody can prohibit you write plugin to parse tables differently, if you can't wait.

**Comment by unindented** [comment]
:+1:

**Comment by puzrin** [comment]
3.0.0 was splitted to plugins. Those can be used as good examples how to make your own, if you decide to create advanced tables plugin.

**Comment by unindented** [comment]
I'll take a look when I find the time. Thanks!

**Comment by jcrben** [comment]
fyi, there's an advanced table plugin implementing multimarkdown tables over at https://github.com/RedBug312/markdown-it-multimd-table
