### ISSUE TITLE
Add more popular libs to the benchmark

### ISSUE THREAD

**Issue by kof** [markdown-it/markdown-it#235]
Care to add more of them? I am really curious about their performance.

- https://github.com/chjj/marked
- https://github.com/showdownjs/showdown
- https://github.com/jonschlinkert/remarkable
- https://github.com/wooorm/remark

**Comment by puzrin** [comment]
Not interested, sorry. Existing benchmarks are for developpers, not for users, and have specific patterns. Adding more will not help to develop markdown-it better.

User-related benchmarks for "all markdowns" should be a separate project.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it#authors

**Comment by kof** [comment]
all right thanks!
 will create a separate project with ALL markdowns) Will borrow your bench implementation)

**Comment by puzrin** [comment]
No problem. We did it quick & dirty, but if you find it useful - use it as you wish. 

Just keep in mind, that test patterns are not for real world examples, but for separate components. It's a reason why we stay aside from "speed compare" talks. In general, speed is much faster than you may ever need :). Key points are features & ease of extension/maintenance (may be script size for client).

**Comment by kof** [comment]
Thats true, I am concerned about speed because I have a very specific usage. We are building a chat and render messages with markdown. This means that markdown needs to be parsed while scrolling at 60fps. Another point as you said is customization. We don't need actually all the features, we have a relatively small subset we support. Removing features should result in a great performance benefit if the implementation is really customizable.

**Comment by kof** [comment]
Also as we need to use it on the client, the size of the library does matter.

**Comment by puzrin** [comment]
60fps is very low requirement, not serious to care about.

- `marked` is smallest but it's the only advantage :), see the number or unresolved issues.
- i don't know about `remark`, but it has good support and good author.
- `remarkable` - see my link to readme in post above :)
- `markdown-it` is ~ 30K gzipped. Can be reduced, if someone:
  - replace `entities` package for browser build with hack https://github.com/markdown-it/markdown-it/issues/6. I'm not strong in this area and can't test shuch hack for compatibility.
  - drop linkifier (it's really one of the best)
- snowdown - ancient.

At our projects 30K is acceptable price for having no problems with quality, security, and flexibility :). We did not reduced size because have more important & interesting tasks.

**Comment by kof** [comment]
I see, thanks for the insights!

**Comment by kof** [comment]
Right now we are doing tests, got already some great results. As we need to parse markdown on 4 platforms: web, ios, android, wp. It's  a huge pain to get consistency in parsing. So we are evaluating parsing markdown in javascript on all platforms. So far we got ios test, our test message with all things we need to support performs at 50k op/s. This is f..g great.
