### ISSUE TITLE
Rewrite URL normalizer

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it#29]
Current normalizer is not correct. I had no time to do it right, because that's related to CommonMark spec and tests. Now all major problems solved, and it's time to care about details.

Reading:

- https://en.wikipedia.org/wiki/URL_normalization

Implementation candidate:

- https://github.com/defunctzombie/node-url (+4.7k gzipped, sorry)
- https://github.com/petkaantonov/urlparser/blob/master/src/urlparser.js - fast parser, but without normalizer

**Comment by puzrin** [comment]
Created ticket in CommonMark tracker https://github.com/jgm/CommonMark/issues/270, need to discuss first.

**Comment by opennota** [comment]
`normalizeLink()` would break certain URLs:

``` js
var normalizeLink = require('./common/utils').normalizeLink;
console.log(normalizeLink('http://example.com/?q=%3f'));
```
Output: `http://example.com/?q=%253f`

``` js
var md = MarkdownIt();
console.log(md.render('[link](http://example.com/?q=%3f)'));
```

Output: `<p><a href="http://example.com/?q=%253f">link</a></p>`

**Comment by tatsy** [comment]
Hello, @opennota. The problem you mentioned is because JavaScript standard function ```encodeURI(code)``` in [util.js](https://github.com/markdown-it/markdown-it/blob/3.0.5/lib/common/utils.js#L186) (excuse me if you already know this).

The problem seems difficult to solve because ```%3f``` corresponds to ```?```. A simple solution to preliminarily replace ```%xx``` to corresponding char does not work for ```?``` because ```encodeURI(code)``` does not encode ```?``` to ```%3f``` or some other characters (Please refer to [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)). 

I'm not sure but the notations ```%xx``` can appear only when non-ascii form data is submitted with GET. So, I think this part of URI should be processed separately in [```normalizeLink```](https://github.com/markdown-it/markdown-it/blob/3.0.5/lib/common/utils.js#L173-L192).

How do you think about this?

**Comment by opennota** [comment]
@tatsy 
I think that normalizer should be rewritten without using decodeURI/encodeURI. It should instead parse URLs and encode different URL parts separately.

**Comment by tatsy** [comment]
Oh, I'm sorry. The last post I wrote was discussed in the issue #49. I agree on that the normalizer should be rewritten without using decodeURI/encodeURI.

**Comment by puzrin** [comment]
See link to commonmark trackerin second post. The only reason, why normalizer not yet rewritten - because commonmark tests (spec) should be fixed.

If it's critical for someone IRL, ping me with example, and priority will be increased.

**Comment by puzrin** [comment]
Attempt to use `url` package added a lot of broken tests from spec :(

https://github.com/jgm/CommonMark/issues/270#issuecomment-75429014

Postponed again.

**Comment by puzrin** [comment]
Fixed in master.
