### ISSUE TITLE
Make helper/utility functions pluggable?

### ISSUE THREAD

**Issue by revin** [markdown-it/markdown-it#299]
Hi there, thanks as always for markdown-it!

Over in [marky-markdown](https://github.com/npm/marky-markdown) as you may recall we're maintaining a parser that attempts to mimic GitHub's markdown parsing, which basically means tweaking things where they deviate from CommonMark processing (definitely a…non-trivial…number of differences). For the most part, writing new parser or renderer rules works great for us; the configurability there is really nice.

One of the things we need to support is that GitHub still allows spaces in link destinations, image paths, etc... For us to be able to change, for example, the parsing of image locations, we need to make a small change to `parse_link_destination()`, but since markdown-it's helper/utility functions aren't accessible through the main parser instance, this means duplicating quite a bit of code in order to make a new rule that calls our own modified helper.

This kind of work would be much easier on our end if we could inject or override the helper functions at runtime, similar to how we can modify the main rule chains. Is that something you would consider implementing?

**Comment by puzrin** [comment]
Hm... i'd say, minimal plugable code unit is "rule". Those link helpers are very specific, to share some code between link/image, and if i try to define some kind of API, that can be ass pain for future compatibility. In fact, link/image rules logic is monolytic (mostly due markdown nature), that mean any attempt to split it will produce ugly result.

I have no good ideas to recommend righ now. Only unpleasant one - copypaste rules sources and use those until better approach invented. But i understand your needs and i'm open to suggestions.

@rlidwka ?

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/8.0.1/lib/index.js#L341

It seems we already exposed those helpers for plugins, but did not used those properties in calls from internal rules. As far as i understand:

- we should use clone, to allow local changes (for any parser instance)
- use those props instead of direct `require()` in link/image rules

That should solve your problem without api change in markdown-it.

**Comment by puzrin** [comment]
Solved by https://github.com/markdown-it/markdown-it/commit/f5a06ec0b626d857d06382e7b8709d943d6f2000, enjoy!

PS. I'd recommend to cover helper modifications with tests, because not sure about signatures stability. Those were not changed for 1.5 years, but i still don't like to promise "official" support.

**Comment by revin** [comment]
Oh that's perfect, thank you so much! And yes, I totally hear you on the "official" support angle, perfectly fine by us. 😄
