### ISSUE TITLE
"^**superbold**^" not parsing as expected

### ISSUE THREAD

**Issue by jackycute** [markdown-it/markdown-it#309]
The `^**superbold**^` should be display as superscript **and** bold,
but **only the superscript works**, the `**` remain unparsed ... :confused:
`**^superbold^**` **doesn't work** as well. `**lol^superbold^**` somehow **works perfectly**.

*The same behavior applies to`^**supercursive**^`, ...*

issue from: https://github.com/hackmdio/hackmd/issues/267

**Comment by puzrin** [comment]
`^....^` is a https://github.com/markdown-it/markdown-it-sup plugin, not this package. But i can say right now - it does not support recursive markup intentionally until spec available. You can play with pandoc to see other edge cases.

In short - replace plugin with your own if you can't wait.

**Comment by jackycute** [comment]
Thanks @puzrin 
Sorry I forgot it's another package.
Nice work 😄

**Comment by puzrin** [comment]
Clarification - that plugin was added to match majority of cases, like "19<sup>th</sup>" & "H<sub>2</sub>O", without recursive markup until situation become more clear. Initial markup source - pandoc.

**Comment by brainscript** [comment]
@puzrin Please add support for that! :cat: I think many people use Markdown as a more effective way to format text they would otherwise format with HTML (or because they can't use HTML in that case).

And seeing Markdown as an "abbreviation" of HTML you can (**_very_** simplified) say that specific characters (or character combinations) are being converted into HTML opening and closing tags.

`**Hi!**` :arrow_right: `<b>Hi!</b>` :arrow_right: **Hi!**
`*Hi!*` :arrow_right: `<i>Hi!</i>` :arrow_right: *Hi!*

---

That's why I expected to be able to also use this nesting inside `^...^`, just like I can with HTML itself.

`^**Hi!**^` :arrow_right: `<sup><b></b></sup>` :arrow_right: <sup>**Hi!**</sup>

---

Although this is not part of the Markdown specification I would still implement it, because ...
- It's not too complex to implement.
- It's a feature users might expect to work (I do :smile_cat:).
- There's also nothing else you would expect to happen when typing `^**blabla**^`.
- There are no disadvantages.

**Comment by puzrin** [comment]
@brainscript sorry, no time for that now. Good implementation is not as easy as it seems and requires spec clarification. You can write your own plugin if you wish.

**Comment by puzrin** [comment]
Please, understand me right - this feature is not implemented not because i don't like it. We investigated it deep, and decided to do partial implementation because "it's better than nothing". But we can't do the rest in nearest future.

**Comment by jackycute** [comment]
I understand that @puzrin 
Following specs and making good implementation are always important since this is kinda of standard lib.
I would like to fork and wait until it's more clear.
