### ISSUE TITLE
Token stream, type `html_inline` - Should "tag" also be tracked here?

### ISSUE THREAD

**Issue by dsifford** [markdown-it/markdown-it#320]
Hi there,

Great work on this project. Very well-thought and executed.

Quick question:

I'm playing around with the token output that markdown-it produces and I noticed that the `tag` property of type `html_inline` is not tracked. Is there a reason for this? It seems like adding this in would be pretty straightforward, no?

Example [here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cspan%20class%3D%5C%22myClass%5C%22%3ESpan%20Content%3C%2Fspan%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D)

Thanks for the clarification!

**Comment by puzrin** [comment]
markdown parser does not understand html. It consider it as "raw output with anything inside".  Since html can have much more info that just tag name and can have wrong format (pairing), there no reason to try fill info partially. We can guarantee only one thing - raw string. Everything else is left to user.

Also, this parser was specially designed to allow work without html (via plugins). So, html support is as minimal as possible.

**Comment by dsifford** [comment]
Thanks for the response. Hm, I guess I'm still not fully understanding. Or perhaps I'm not fully understanding the limits of the parser.

Intuitively speaking, and speaking directly to the example provided above, since the parser is aware that the child of the `inline` type is an `html_inline` type with the following shape...

```js
"children": [
      {
        "type": "html_inline",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "<span class=\"myClass\">",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      },
      {
        "type": "text",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "Span Content",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      },
      {
        "type": "html_inline",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "</span>",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      }
    ],
```

And since it is able to realize that it is an `inline_html` type, and is able to detect that it starts and ends with `<span class=\"myClass\">` and `</span>`, respectively, then why would it not also be able to populate the `tag` property with `span`, considering all HTML elements names contain only letters a-z, begin with a `<` or `</` and end with a space or `>`?

Is this for security reasons or something along those lines that I might be overlooking?

Thanks so much for the clarification!

**Comment by puzrin** [comment]
It's a result of conservative approach in design - don't provide data that not needed and don't provide incomplete api (api includes data design too). Because that can cause api break in future.

You may need tags for html, but other people may need classes, data attrs and other things. And since idea is to avoid partial implementations and provide minimal support for html, it's more simple to keep API clear and fill only "content" for html tokens, IMHO. Until better ideas available. Also that helps to keep html block tokens and html inline tokens similar. I agree, that additional info can be useful sometime, but we should care about general data integrity too.

**Comment by dsifford** [comment]
Understood, and totally respect your decision. I appreciate the insight; always nice to be able to get a glimpse of the bigger picture through the lens of a project's brainchild 😄

**Comment by wtto00** [comment]
Hello, sorry to bother you. I would like to know if there are any related plugins to convert `html_inline` or `html_inline` into a tag structure?

Current output is:
```json
{
  "type": "html_block",
  "tag": "",
  "attrs": null,
  "map": [
    22,
    24
  ],
  "nesting": 0,
  "level": 0,
  "children": null,
  "content": "<p class=\"abc\">123</p>\n___\n",
  "markup": "",
  "info": "",
  "meta": null,
  "block": true,
  "hidden": false
}
```
But I want to obtain a `p` tag and a `text` tag, and I haven't found a related plugin to do this.
