### ISSUE TITLE
AST output for component-based renderers

### ISSUE THREAD

**Issue by ccorcos** [markdown-it/markdown-it#326]
Have you considered generating and intermediate AST so we can use component-based renderers like React with markdown-it?

**Comment by puzrin** [comment]
You can call `.parse()` and then build any AST you need from output flat data. This does not require any change in core, and is not difficult.

**Comment by puzrin** [comment]
Also, there are some plugins available for react in npm, but i'm not familiar with details.

**Comment by ccorcos** [comment]
interesting. so you're saying it would make more sense to just use an XML parser to create the AST. not a bad idea... thanks for the help

**Comment by ccorcos** [comment]
Hey @puzrin just wanted to tell you about a library I just published using this approach you suggested.

https://github.com/ccorcos/markdown-it-renderer

Please let me know if you have any feedback.

**Comment by episodeyang** [comment]
@ccorcos haha I wrote one too, but you beat me to publishing it.

How do you key components in a list so that the tail end does not get re-rendered when the first part gets updated?

I have slow math rendering components that should be updated only when needed, and if the user edits the front part of a paragraph, the tail end of the paragraph flashes because my keys are array indexes.

**Comment by ccorcos** [comment]
I don't have any keys. React handles substitutions like that without having keys I believe.

**Comment by episodeyang** [comment]
don't you need keys for components inside an array? Otherwise react
complains.

**Comment by ccorcos** [comment]
What array?
