### ISSUE TITLE
Copyright concern

### ISSUE THREAD

**Issue by petebacondarwin** [markdown-it/markdown-it#328]
Hi @puzrin and @rlidwka 

I would really like to use this project in `dgeni-packages` but I am blocked on your outstanding disagreement with the owner of remarkable. Clearly this project is a fork of that other one. And clearly you were both the primary contributors to that project. So I understand that you feel ownership over the code. But at the same time you agreed to release that previous code under the MIT license which does indeed require that copyright is attributed in projects that build on substantial parts of that project, which it appears to me that this is.

Can I suggest a possible solution would be simply to include the original project's copyright notice in your license file, that indicates that this project had its roots in that one. Similar to what remarked does here: https://github.com/jonschlinkert/remarked/blob/master/LICENSE-MIT#L2
So in your license it would look something like:

>Copyright (c) 2014-2017 Vitaly Puzrin, Alex Kocharin.
>Copyright (c) 2014 Jon Schlinkert, Vitaly Puzrin (https://github.com/jonschlinkert/remarkable).
>
> Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
>

In this way you make it clear that there is limited copyright attributed to the previous project, as indicated by the limited timescale on the attribution, which would seem to alleviate any claim that remarkable has over any copyright violation.

Note that I am no lawyer and this is all hand waving on my part. But I hope that such an act would allow you to come to an agreeable solution with @jonschlinkert and allow projects like mine to make use of your tool.

**Comment by puzrin** [comment]
I don't agree with your vision of situation. Jon Schlinkert was added to copyright string by mistake (in advance, because he fooled me with false promises) and he was not a copyright owner. So, there was nothing wrong with fixing copyright as it was done. As a copyright owner for the moment of repo move, i didn't need his opinion and his agreement for such change. I think, it's better ask him fix wrong copyright in old repo, if anyone wish waste time for that. Because formally, from my point of view, invalid copyright content is in `remarkable` repo.

There is a legal way to resolve such collisions - anyone can try write DMCA complain to github and escalate it to court of justice after such complain will be declined by me. If i get a legal decision that copyright string fix was incorrect, it will be updated as you said. Without such decision everything else is just a talks, and copyright content here will stay intact.

**Comment by petebacondarwin** [comment]
I completely understand your point of view and I don't blame you. But sadly this means that unless someone does get some kind of definitive legal answer about this we will have to use another library. :-(

**Comment by puzrin** [comment]
I understand you. IMHO parent packages can not be affected, because license will stay MIT anyway and you are not responsible for my actions. But if you think that's critical for your project - it's only your choice to use or not to use `markdown-it`.

**Comment by jonschlinkert** [comment]
> I don't agree with your vision of situation. Jon Schlinkert was added to copyright string by mistake (in advance, because he fooled me with false promises) and he was not a copyright owner.

To this point I've remained quiet despite your repeated public dishonesty and not respecting the copyright on remarkable. I'm the copyright owner of remarkable, this is a fork of that project. As you know (and the entire world can see for themselves), what is now called "remarkable" initially was called [remarked](https://github.com/jonschlinkert/remarked/commits/master), which itself was a fork of marked.js. 

You contacted me and asked if you could contribute to that project. I asked you why you contact "me"?, and you gave a couple of reasons, including that you thought my approach was better than other libraries you found. I said yes and you said you wanted to do a lot and potentially make major changes. I said that would be great, then we went back and forth in an email discussion about what that would mean. 

In one of your emails, which I posted publicly in its entirety the last time you made this claim, you stated that you did not expect me to contribute in any way, you only wanted to "use my name" and you had some time to give and needed a new markdown parser with certain features. I made it clear that I was busy raising funding, and I didn't know how much time I would have to work on the project. You reiterated that it was fine as long as you could do the work "under `github.com/jonschlinkert`" and that if I decided to leave node.js "like TJ" (in your words) that I would transfer the project to a different account (fwiw I'm still here). 

I agreed to it and added you and other collaborators of yours to [remarked](https://github.com/jonschlinkert/remarked/commits/master), where we continued work on that project. 

Soon after that, I suggested that we rename the project, as I thought of a new name, `remarkable` and was excited about the project., We both thought it would be a good idea. Thus, we created `remarkable`, seeded with some of the utility code from _remarked_. We spent quite a bit of time discussing how the code would work, what the API would be, and what features it should have. I also spent time explaining to you how we could increase awareness by improving SEO by doing certain things in the readme (and even code comments). You replied that you always thought my readmes were too verbose and wordy, and that developers will never read all of that, but now it made sense why I wrote so much (for SEO).  I think any person familiar with open source would agree that any time spent at all is considered contributing. It doesn't need to show in the commit history, and saying it does is dishonest (although I can't say it's surprising that @puzrin [doesn't respect my contributions](https://github.com/jonschlinkert/remarkable/pull/65#issuecomment-60535605)).

Not long afterwards, the project started getting stars, and was mentioned on reddit, and you started publicly making negative comments about me and how "I wasn't doing anything" and you were the only one making commits.  That alone was fine, I can deal with that. But then you started being combative in normal discussions, and it seemed fairly obvious that (because of the project's success), you regretted deciding to do the work under my name. For no good reason at all, you started threatening to move the project.

You might have regretted your decision, but unfortunately, that's too bad. You like to tell people I "didn't do anything" because you can conveniently point to the commit history on remarkable, forgetting to mention that the codebase started with remarked and that I helped with other high level things (including the inspiration behind the projects in the first place). Regardless, even if I didn't make a single commit, that doesn't make you entitled to the copyright. I wouldn't even care about this if you didn't keep saying dishonest things about it publicly. 

Because of your dishonest claims here and on the commonmark forums, every once in a while, since this all started, I get rude comments from people who have no clue what really went down, and have the misguided belief that you did me some kind of favor. To clear the air, my projects, not including remarkable, were downloaded 5 billion times in the past 12 months, which accounts for nearly 6% of the total downloads on NPM. Remarkable's downloads equate to 0.0002% of that number. IMHO, "my approach" and my guidance to building the API, along with my reputation, were arguably just as important to what made that project successful. 

In this project, markdown-it, I'm fine with you saying whatever you want about why you forked it from remarkable, but if you continue to make dishonest comments about my involvement, and don't add me back to the copyright, I'll be forced to ask for a DMCA takedown, which is the absolute last resort and something I would never want to do to an open source project. But I have an email trail and git history to prove my involvement, and the backlash I'm getting from this is getting ridiculous.

**Comment by jonschlinkert** [comment]
also, fwiw I'd be happy to take a pr to merge all updates in markdown-it to remarkable so we can continue development on the original project. I also have more time to spend updating code.

**Comment by puzrin** [comment]
I've removed BS comments from @jonschlinkert since i'm not going allow him to use my repos for abuses and waisting my time.
