### ISSUE TITLE
Have you considered to import Math(TEX, MathML...) support ?

### ISSUE THREAD

**Issue by harttle** [markdown-it/markdown-it#33]
Since markdown is widely used by developers, it's useful to support code block. While, for those who have math background, math support can be equally helpful.
I ever extended from chjj/marked to buddys/marktex, which add math block. It's troublesome to maintain a repo by myself, shall I join you ?

Here is one of my blog containing many math blocks (once a time it's powered by buddys/marktex):
http://harttle.github.io/reading/introduction-to-algorithms.html

**Comment by puzrin** [comment]
http://talk.commonmark.org/t/mathematics-extension/457

1. IMHO math support is very useful feature, but it doesn't yet have final agreement about markup.
2. I see no technical problem to implement it via plugin. The only problem is, that markup can become incompatible, when math support lands in commonmark spec.

[KaTeX](https://github.com/Khan/KaTeX) - new interesting lib for TeX math rendering.

What kind of help do you need? markdown-it is specially designed for syntax extendability. One of goals was to allow plugin developers to be independent on main repo.

**Comment by vyp** [comment]
KaTeX is very fast, but the reason is because it implements only a subset of what mathjax can render. So if this feature happens, perhaps provide support for both, but have an option to choose the renderer. Maybe it's possible to use katex, and then fallback to mathjax for anything katex cannot handle but I presume that functionality is out of scope for this project.

**Comment by puzrin** [comment]
I think, 2 different plugins can be better - more easy to bundle for browser. KaTeX for some reasons is almost not updated after release, and has very big tail of pending PRs :(

As far as i understant, @harttle had problem because he had to support full parser clone, but with markdown-it this problem does not exists. Block rule can be cloned from `fences`, inline rule can be cloned from `emphasis`. All with very small changes.

Anyway, this will not go to core. I'll keep this issue open for short time, if anyone has questions about implementation.

**Comment by vyp** [comment]
Sounds good. Definitely agree with not going in core.

**Comment by harttle** [comment]
Yeah, TEX block markup should be a plugin, I'll consider to implement that.
Since block rule can be cloned from `fences` , it sounds easy to do that. Thank you!

**Comment by puzrin** [comment]
No problem. I'm closing this ticket, but feel free to create new one if you have some difficulties.

If you need blocks only, without inlines, and you are ok with fenced format like this:

~~~
```tex
...
``
~~~

Then only renderer patch needed, something like [this](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer).

**Comment by servermeta** [comment]
interesting thread. Commenting to keep track of it.

**Comment by mgeier** [comment]
Just for reference, there is a plugin that handles LaTeX math quite well: https://github.com/classeur/markdown-it-mathjax
