### ISSUE TITLE
Help with a simple plugin

### ISSUE THREAD

**Issue by ccorcos** [markdown-it/markdown-it#333]
I want to create a plugin that parses out `[Name]{JSON}` where `Name` is some arbitrary string and JSON can be parsed with `JSON.parse`. I thought it would be as easy as looking at the `link` example, but it doesnt appear to be that simple.

**Comment by puzrin** [comment]
What kind of help do you expect? We do not write plugins by request.

**Comment by ccorcos** [comment]
I get that, I'm just unable to figure out where I should start. I read through the docs here:

https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md
https://github.com/markdown-it/markdown-it/blob/master/docs/development.md

But when I look through the source code, there just appears to be a lot more going on. I think it would be great if there were an example of a parser that parses for text between two arbitrary tokens and adds that to the rule chain. I couldnt find any existing plugins that do something simple like that.

Even the backticks file is hard for me to follow:

https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/backticks.js

**Comment by puzrin** [comment]
https://www.npmjs.org/browse/keyword/markdown-it-plugin i'd suggest to search npm for plugins. There should be a lot of simple things. Current situation is, that `markdown-it`'s entry level is above average, and we have no resources to write detailed tutorials for novices. Because that can fall into big book about parsers and programming. So, requests about docs/tutorials improve are not accepted as "endless", only via PR. We can help only when one already tried to implement plugin and has more concrete technical questions.
