### ISSUE TITLE
Error parsing Chinese

### ISSUE THREAD

**Issue by XadillaX** [markdown-it/markdown-it#340]
```javascript
var markdownIt = require("markdown-it")();
console.log(markdownIt.render("**Patchouli 是专注于请求分发、服务分级的 API 网关系统，**为企业更好地整合各后端服务的资源。"));
```

No strong wrapped to `Patchouli 是专注于请求分发、服务分级的 API 网关系统，`.

**Comment by ucev** [comment]
add a space  after `**` block works fine.
var markdownIt = require("markdown-it")();
console.log(markdownIt.render("**Patchouli 是专注于请求分发、服务分级的 API 网关系统，**  为企业更好地整合各后端服务的资源。"));

**Comment by XadillaX** [comment]
@ucev I know. But in fact, a space shouldn't appear after Chinese punctuation (Chinese comma, etc.)

**Comment by ucev** [comment]
Maybe it has some matter to do with `markdown parsing regexp`, use it as a paradigm is just ok.

**Comment by puzrin** [comment]
[Works as expected](http://spec.commonmark.org/dingus/?text=**Patchouli%20%E6%98%AF%E4%B8%93%E6%B3%A8%E4%BA%8E%E8%AF%B7%E6%B1%82%E5%88%86%E5%8F%91%E3%80%81%E6%9C%8D%E5%8A%A1%E5%88%86%E7%BA%A7%E7%9A%84%20API%20%E7%BD%91%E5%85%B3%E7%B3%BB%E7%BB%9F%EF%BC%8C**%E4%B8%BA%E4%BC%81%E4%B8%9A%E6%9B%B4%E5%A5%BD%E5%9C%B0%E6%95%B4%E5%90%88%E5%90%84%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E7%9A%84%E8%B5%84%E6%BA%90%E3%80%82)

This package just implements commonmark spec, it's not about markdown markup definitions. Spec-related issues are not accepted here. You should ask at https://talk.commonmark.org/.

**Comment by puzrin** [comment]
See [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2APatchouli%20%E6%98%AF%E4%B8%93%E6%B3%A8%E4%BA%8E%E8%AF%B7%E6%B1%82%E5%88%86%E5%8F%91%E3%80%81%E6%9C%8D%E5%8A%A1%E5%88%86%E7%BA%A7%E7%9A%84%20API%20%E7%BD%91%E5%85%B3%E7%B3%BB%E7%BB%9F%EF%BC%8C%2A%2A%E4%B8%BA%E4%BC%81%E4%B8%9A%E6%9B%B4%E5%A5%BD%E5%9C%B0%E6%95%B4%E5%90%88%E5%90%84%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E7%9A%84%E8%B5%84%E6%BA%90%E3%80%82%5Cn%5Cn%2A%2APatchouli%20%E6%98%AF%E4%B8%93%E6%B3%A8%E4%BA%8E%E8%AF%B7%E6%B1%82%E5%88%86%E5%8F%91%E3%80%81%E6%9C%8D%E5%8A%A1%E5%88%86%E7%BA%A7%E7%9A%84%20API%20%E7%BD%91%E5%85%B3%E7%B3%BB%E7%BB%9F%2A%2A%2C%E4%B8%BA%E4%BC%81%E4%B8%9A%E6%9B%B4%E5%A5%BD%E5%9C%B0%E6%95%B4%E5%90%88%E5%90%84%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E7%9A%84%E8%B5%84%E6%BA%90%E3%80%82%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). Looks like you have comma in wrong place.

**Comment by episodeyang** [comment]
@puzrin just want to point out that in the example you are using the Latin comma, not the double-width CJK comma.

**Comment by puzrin** [comment]
@episodeyang 

1. i've taken reported string and copy-pasted comma to proper place.
2. all unicode punct chars are recognized properly https://github.com/markdown-it/markdown-it/blob/8.3.1/lib/rules_inline/state_inline.js#L88-L89

**Comment by XadillaX** [comment]
@puzrin 

In fact:

`**（中文）**和**（英文）**的区别` wanted to be

> **（中文）**和**（英文）**的区别

**Comment by XadillaX** [comment]
The different between Chinese and Latin punctuations is **SPACE**.

Space is not recommend to insert after a Chinese punctuation but should after a Latin punctuation.

**Comment by puzrin** [comment]
@XadillaX you are right, but that's general markdown/commonmark problem, not specific to this package. It's better to discuss such things on commonmark forum, because we stay aside from markup definition.

**Comment by episodeyang** [comment]
> i've taken reported string and copy-pasted comma to proper place.

@puzrin It looks like your pasted comma in the link turned into a single-width latin comma. Highlight shows the original with double-width.

>[original example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2APatchouli%20是专注于请求分发、服务分级的%20API%20网关系统，%2A%2A为企业更好地整合各后端服务的资源%E3%80%82%5Cn%5Cn%2A%2APatchouli%20是专注于请求分发、服务分级的%20API%20网关系统%2A%2A%2C为企业更好地整合各后端服务的资源%E3%80%82%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

![screenshot 2017-03-11 12 13 01](https://cloud.githubusercontent.com/assets/630490/23825719/76678ce8-0654-11e7-9ac5-192c608a94f9.png)


---
Here is one that uses double-width comma in both two lines. As per your second comment, it does work.

[fixed example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2APatchouli%20是专注于请求分发、服务分级的%20API%20网关系统，%2A%2A为企业更好地整合各后端服务的资源%E3%80%82%5Cn%5Cn%2A%2APatchouli%20是专注于请求分发、服务分级的%20API%20网关系统%2A%2A，为企业更好地整合各后端服务的资源%E3%80%82%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

![screenshot 2017-03-11 12 22 52](https://cloud.githubusercontent.com/assets/630490/23825765/8e9fe7e6-0655-11e7-8518-85602f402de5.png)


@XadillaX as Puzrin said, however frustrating this issue is, it is a problem with the `CommonMark` spec (standard). There is a small but active Chinese community on the CommonMark forum, and I really think users like you and I should bring up these issues there, and see if there could be a change in the standard to make CommonMark more friendly towards CJK inputs. 

These changes takes consensus and time, but if nobody put in the work to push for it, nothing will change.

Link to the forum is here: [CommonMark](https://talk.commonmark.org)

**Comment by tats-u** [comment]
This is due to [the definitions of left- & right-flanking delimiter run](https://spec.commonmark.org/0.30/#left-flanking-delimiter-run) introduced in CM 0.14+. They are designed under the erroneous assumption that all languages (including Chinese and Japanese!) included spaces around punctuation marks.
They must be revised like https://github.com/commonmark/commonmark-spec/issues/650#issuecomment-1850363984 for this issue to be fixed.
