### ISSUE TITLE
Links are broken when containing parenthesis character ")"

### ISSUE THREAD

**Issue by x9t9** [markdown-it/markdown-it#354]
### Expected behavior : 

Valid and safe URL's  pasted or written should be converted to functional links ( as-is ) .

### Actual behavior : 

Valid and safe URL's that contain the parenthesis closing character ` " ) " ` are immediately  broken at the point of said character .

### Steps to reproduce : 

- Open the [markdown-it demo](https://markdown-it.github.io) 
- Paste a URL ( or write one ) 
- Manually add a closing parenthesis character in the link ` " ) " ` . 

Note : As per my understanding , the parenthesis character ` " ) " ` IS considered safe and valid as per   [rfc3986](https://tools.ietf.org/html/rfc3986) ( see also [here](http://stackoverflow.com/questions/1856785/characters-allowed-in-a-url)  and [here](http://stackoverflow.com/a/1547940/1244126) )

**Comment by puzrin** [comment]
That's a result of linkifier work. And it has reasons to consider unpaired ")" as outer char. If you don't like it - you can always define links via markdown syntax.

PS. online demos has possibility to create permalinks. Real example is better that description of steps to reproduce.

**Comment by x9t9** [comment]
@puzrin I am not sure I understand why this was closed ( is it because the description or because it is not a bug or because it is in the wrong place ) and also what you mean by define link explicit . 
In every way that I tried , the following link is somewhat broken ( as display or link itself ) 

`http://stadtplan2.dresden.de/(S(p5l1235ice3cj3lspsbkmdnb))/spdd.aspx?TH=GA_KLG`

Is that the real example you were referring to ?

**Comment by puzrin** [comment]
Because that's not a markdown-it bug, and if you define your link according to commonmark spec, it will work as expected. That may be considered as linkify-it it bug, but it's known and nobody can give you 100% guarantee for heuristic anyway. If you need 100% guarantee, you should format links with commonmark syntax as described in spec.

> Is that the real example you were referring to ?

[The best way to show example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22---%5Cn%5Cnthat%27s%20euristics%2C%20it%20may%20fail%20sometime.%20For%20example%2C%20with%20nested%20scopes.%5Cn%5Cnhttp%3A%2F%2Fstadtplan2.dresden.de%2F%28S%28p5l1235ice3cj3lspsbkmdnb%29%29%2Fspdd.aspx%3FTH%3DGA_KLG%5Cn%5Cn---%5Cn%5Cnmarkdown%20link%2C%20ok%3A%5Cn%5Cn%3Chttp%3A%2F%2Fstadtplan2.dresden.de%2F%28S%28p5l1235ice3cj3lspsbkmdnb%29%29%2Fspdd.aspx%3FTH%3DGA_KLG%3E%5Cn%5Cn%5Btext%5D%28%3Chttp%3A%2F%2Fstadtplan2.dresden.de%2F%28S%28p5l1235ice3cj3lspsbkmdnb%29%29%2Fspdd.aspx%3FTH%3DGA_KLG%3E%5Cn%29%5Cn%5Cn%5Btext%5D%28http%3A%2F%2Fstadtplan2.dresden.de%2F%5C%5C%28S%5C%5C%28p5l1235ice3cj3lspsbkmdnb%5C%5C%29%5C%5C%29%2Fspdd.aspx%3FTH%3DGA_KLG%5Cn%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by x9t9** [comment]
Understood .
Sorry for missing that `permalink` tab link .. :-)
