### ISSUE TITLE
Is entities really needed?

### ISSUE THREAD

**Issue by SamSaffron** [markdown-it/markdown-it#365]
We started looking at upgrading Discourse to Markdown.it 

At the moment I am in the middle of adding an "experimental" switch for it. 

During my work I was trying to figure out why markdown.it is so much bigger than our previous md library. One thing that stuck out is https://github.com/fb55/entities/blob/master/maps/entities.json which is 39k. 

Is this dependency really required? Should it be an opt in thing to keep the bundles small by default?

**Comment by puzrin** [comment]
Hi Sam :) !

## Overview

At first, i'd suggest to measure gzipped and minified files, because uncompressed size does not reflect real downloads. There are 2 big places with text constants:

1. html entities
2. [regexps in linkify-it](https://github.com/markdown-it/linkify-it/blob/master/lib/re.js) (+ imports from uc.micro)

I'd suggest to take file from `/dist` folder, cut code in editor, minify, gzip, and then decide if possible win make sense for you.

## Entities

> Is this dependency really required? Should it be an opt in thing to keep the bundles small by default?

1. That's required by commonmark standard, because it should support entities.
2. I think it's not good idea to drop this by default.

But probably, your question is "Is this dependency required **in browser**?". I think, it's possible to use hack via textarea to convert entities. If you can guarantee DOM availability. But i'm not strong in browser programming and can't organize good testing.

If you decide to hack entities, we could accomodate your achievements as additional build in `/dist` folder. Or, if you use webpack, you can customize config to replace `entity` dependencies with your lite implementation.

**Comment by puzrin** [comment]
I'd suggest to close "floating" issue to keep tracker clear. When you decide to move forward, you can reopen or create a new one.

**Comment by SamSaffron** [comment]
no problems, will open a new one once I get to this state
