### ISSUE TITLE
Make inline text tokenization more flexible

### ISSUE THREAD

**Issue by SamSaffron** [markdown-it/markdown-it#370]
At the moment when you register an inline you can sometimes be surprised never to be called if the text rule skipped you. 

Additionally you are called a bit too frequently, for example the emphasis rule may be called with a `+` token and quickly ignore it cause the char code does not match. 

I was thinking, perhaps we can amend the inline ruler to accept a list of stop chars and do away with the text ruler.  

eg:

```
md.inline.ruler.after('emphasis', 'sup', superscript, '^');
md.inline.ruler.push('emoji_replace', emojiReplace, ';:8<>');
```

That way an object can be built that efficiently dispatches to the correct rules base on a single lookup, and this would be extensible. 

```
{
   "^", [fn1,fn2,fn3], 
    ";", [fn5],
    ... etc ..   
}
```

The API would be breaking, but I think it may be worth it. 

Thoughts?

**Comment by puzrin** [comment]
> Thoughts?

In every project... every new person... encouraged with new ideas... may think that developers are idiots who are not familiar with obvious things :). That's normal, it's a life :)

Constructive talk about optimizations mean:

1. You can provide benchmarks or estimates (at least)
2. This optimization is in critical chain and effect is good enougth (added value)
3. Cost of maintenance is acceptable (code readability + api convenience + ...)
4. Someone has time and desire to implement those things

You should not believe to my words, but quick answer (= experienced preliminary estimate) is "cummulative added value will be zero or negative" :)

In other words, i'd suggest you to wait couple of month with such suggestions. After you will get more info about `markdown-it` internals, you will change your first impression very much.

> I was thinking, perhaps we can amend the inline ruler to accept a list of stop chars and do away with the text ruler.

That will not make code faster (i think so), but will make api more complicated and code more close-coupled. IMHO it's not a good practice to bump internal details (charcodes) to upper/external API. To make this right, you will have to introduce more intermatiade api layers. Existing logic is already non-trivial. No need to increase nightmare level without very strong reasons.

---

Of cause, i can not prohibit you to experiment :). But, IMHO, there are more important things to spend programmer's time, if anyone has it: https://github.com/markdown-it/markdown-it/issues/125

Also, make sure to read something like http://mrale.ph/ (about JIT optimizations). Because if something looks fast in your eyes, it can be not fast in JIT.

**Comment by SamSaffron** [comment]
> In every project... every new person... encouraged with new ideas... may think that developers are idiots who are not familiar with obvious things :).

For the record this is very far from my experience with markdown.it, I have worked with 3 md engines to date (showdown, evilstreak markdown js and markdown it) this is the first engine I have used that actually makes sense and is designed in a sane and extensible way. 

The engine makes sense, I do not think the developers are idiots. 

> You can provide benchmarks or estimates (at least)

I did start with this per: 

https://jsperf.com/bench-is-terminator

But will do a fuller benchmark on a proof of concept next week. 

> i'd suggest you to wait couple of month with such suggestions. 

The trouble is that in a couple of months I will have moved on to another project, I am working full time at the moment porting all the extensions and plugins Discourse has to markdown.it, I found extreme friction around implementing this: https://github.com/discourse/discourse/blob/markdownit/app/assets/javascripts/pretty-text/engines/markdown-it/emoji.js.es6#L237 cause I needed to make a bunch of helpers and also I did not like that I was double scanning text when an inline would have done the trick if it was extensible.

**Comment by puzrin** [comment]
Sam, there is `/benchmark` folder, where you can test your averaged text. IMHO, current implementation is fast enougth. You can check it. And if it's fast enougth, there are no reasons to spend time for unclear experiments.

Also, IMHO, your proposal will not improve speed in JS, but i can not prove it (= i can not spend a lot of time to prove it).

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/lib/ruler.js

At first glance, most of signatures are already extendable. Only "getRules" should be extended with second optional param. So, things can be done without API break (old plugins will work in old mode).

But i doubt, that it's possible to get significant boost in JS. May be, via autogenerated functions, but that will be not compatible with restrictive CSP. I already experimented with generated code to avoid functions lookup via tables, but had no success.

**Comment by SamSaffron** [comment]
Yes, I can see the macro bench does repro the 10% hit on readme.md for any dynamic based lookup (array or object). I still want to experiment with this for a bit more to see if it ends up being an overall win for emoji replace. Will update here with my findings. Worst case I can create an extra dynamic inline ruler for our internal use that is applied in a core rule. I am sort of doing that now anyway.

**Comment by puzrin** [comment]
As far as i remember, emoji replacer is not "inline". It will not be affected if you are not going to rewrite it too,

**Comment by puzrin** [comment]
closing :) ?

**Comment by SamSaffron** [comment]
yes you can close, I can defer on this for now :)
