### ISSUE TITLE
Parser state API docs

### ISSUE THREAD

**Issue by ccorcos** [markdown-it/markdown-it#415]
I'm trying to understand state.push in this bit of code but I cant seem to find it in the documentation.

```
	// Earlier we checked !silent, but this implementation does not need it
	token = state.push("sup_open", "sup", 1)
	token.markup = "^"

	token = state.push("text", "", 0)
	token.content = content.replace(unescapeRe, "$1")

	token = state.push("sup_close", "sup", -1)
	token.markup = "^"
```

**Comment by puzrin** [comment]
There are no docs for deep internals. And it will not appears, because we have no resources for this. The only way to understand is to dig code of this package and other plugins.

https://github.com/markdown-it/markdown-it/blob/master/lib/rules_inline/state_inline.js

Code from your cite push 3 tokens: opening, content, closing.

**Comment by ccorcos** [comment]
I see. Thanks for your direction. 

I built a plugin a last weekend -- I'd appreciate any feedback you have: https://github.com/ccorcos/markdown-it-component

The real goal is to be able to render arbitrary react components through this package: https://github.com/ccorcos/markdown-it-renderer

**Comment by windmaomao** [comment]
I'm on this track as well. One of the most interesting piece is `state`, I wish I could just make a map of all states in the core, that'll be kool.
