### ISSUE TITLE
Markdown syntax transforming valid links.

### ISSUE THREAD

**Issue by ccorcos** [markdown-it/markdown-it#458]
I've noticed links with underscored in them get linkified poorly. For example, `http://chetcorcos.com/_italics_` is interpreted as `[http://chetcorcos.com/](http://chetcorcos.com/)_italics_` but I would have expected `[http://chetcorcos.com/_italics_](http://chetcorcos.com/_italics_)`. Meanwhile, I would expect the underscores to be preserved when rendered to HTML.

**Comment by puzrin** [comment]
That's a known issue, discussed somewhere earlier. No plans to fix. Use `<your_link_with_dashes>` as workaround (define link explicit).

**Comment by ccorcos** [comment]
Sadly, in my situation, I'm not exactly in control of the format I'm getting in... I could try preprocessing the text, but ideally we could make it work in here. Would you accept a PR if I figure it out? Were there any technical constraints preventing this when it was last discussed?

**Comment by puzrin** [comment]
See #38. I'll be happy to accept fix, but it's NOT easy to do it right, because:

- That will require linkifier to be part of scanner, to each link end (now it scans after parces, when caontent is already broken)
- But parser toggles state only on limited set of punctuation characters, to be fast. So, you can not handle schema start (`h` for `http`, `f` fot `ftp`). And that will be a total nightmare for fuzzy links and emails.
- Workaround can be to fetch `:` and hack pending buffer to extract schema start validate is somehow.
  - In theory, that will not fix all, but should help with all cases from real world.
  - but it's not easy to validate start properly (see linkifier sources) and keep linkifier api extendable. For example, likifier catch properly things like `>http://...` - quoted text.

But note, this package has high requirements to architecture design quality. If you decide to spend your time to make fix - create issue first with your suggestions.

**Comment by ccorcos** [comment]
I see. May be easiest to have a preprocessing step instead...

**Comment by ccorcos** [comment]
I'm using the following code in the meantime to preprocess the data going into markdown-it. Maybe it could help someone.

```
import * as LinkifyIt from "linkify-it"

interface LinkifyMatch {
	index: number
	lastIndex: number
	raw: string
}

// Wrap links with <> to prevent the markdown parser from interpreting markdown within the link.
function fixMarkdownLinks(markdown: string) {
	const linkify = new LinkifyIt()
	const matches: Array<LinkifyMatch> = linkify.match(markdown)
	if (matches.length === 0) {
		return markdown
	}
	let result: string = ""
	let prevEndIndex = 0
	for (const match of matches) {
		const noStartBracket =
			match.index === 0 || markdown[match.index - 1] !== "<"
		const noEndBracket =
			match.lastIndex === markdown.length || markdown[match.lastIndex] !== ">"
		const shouldInsertBrackets = noStartBracket && noEndBracket

		result += markdown.slice(prevEndIndex, match.index)
		if (shouldInsertBrackets) {
			result += "<"
		}
		result += match.raw
		if (shouldInsertBrackets) {
			result += ">"
		}
		prevEndIndex = match.lastIndex
	}
	result += markdown.slice(prevEndIndex)
	return result
}
```
