### ISSUE TITLE
Some CommonMark 0.17 tests fail

### ISSUE THREAD

**Issue by opennota** [markdown-it/markdown-it#53]
Some CommonMark 0.17 tests in the section "Emphasis and strong emphasis", notably those containing intraword underscores, fail with the current master.

One example is `пристаням_стремятся_` — it should render as `<p>пристаням_стремятся_</p>` and not as `<p>пристаням<em>стремятся</em></p>`.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/tree/master/test/fixtures/commonmark

Currently conformed spec is 0.15. Also there are pending changes in emphasis, discussed on forum. We don't update immediately non critical changes, because it's too time-consuming.

Everything about spec is under the control, dont' worry. If you like to dig code, take a look at https://github.com/markdown-it/linkify-it . It's upcoming replacement for current linkifier, and it really needs intensive testing of edge cases.
