### ISSUE TITLE
Wrap a existing rule's fn in plugin

### ISSUE THREAD

**Issue by Menci** [markdown-it/markdown-it#544]
For example, I want to wrap the table rule's fn, I can do this:

```js
let rule = md.block.ruler.__rules__.find(rule => rule.name === 'table'), oldFn = rule.fn;
rule.fn = () => {
    oldFn.apply(null, arguments)
};
```

But are there any way to do this without accessing hidden API `Ruler.__rulers__`?

**Comment by puzrin** [comment]
We could not imagine why one may need to wrap existing rule, and did not reserved such access methods. But you can try this way:

1. load table from file

https://github.com/markdown-it/markdown-it/blob/d533c27017dbb9663422019a08adcf15265cf9fb/lib/parser_block.js#L15

via `require('markdown-it/lib/rules_block/table')`

2. Wrap it as you need
3. Replace existing via `Ruler.at()`

https://github.com/markdown-it/markdown-it/blob/d533c27017dbb9663422019a08adcf15265cf9fb/lib/ruler.js#L117

---

But i don't think your way is bad. I would only use `Ruler.__find__()` instead for search.

**Comment by KyleMit** [comment]
@Menci , I'll leave here in case this was your similar to your use case.  My goal was to wrap `<table></table>` with a div so I could add scroll support on mobile.

Originally, I was looking to do what you're doing by modifying the way the table parsing works.  It *could* be done by pushing a token to the `state` before `table_open` and another after `table_close`

Something like this in [`table.js`](https://github.com/markdown-it/markdown-it/blob/10.0.0/lib/rules_block/table.js#L67):

```diff
+ token = state.push('table_wrapper_open', 'div', 1);
+ token.attrs = [['class', 'table-wrapper']]
  token = state.push('table_open', 'table', 1);

  // ....

  token = state.push('table_close', 'table', -1);
+ token = state.push('table_wrapper_close', 'div', -1);
```

But that method shouldn't be touched so I tried wrapping it like you're doing, but it's a lot of logic to re-implement and modifying the state outside the scope is hard because it requires modifying the `token.level`

What I wound up doing is updating the rendering, not the parsing - since I'm still going to trust the engine to *parse* tables the same way no matter what

You can override the way particular tokens are rendered as spelled out in the [architecture doc](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md)

A simple implementation looks like this:

```js
let md = markdownIt(options);

// when rendering table, wrap in div container
md.renderer.rules.table_open = function(tokens, idx, options, env, self) {
    return `<div class='table-wrapper'>` + self.renderToken(tokens, idx, options);
};
md.renderer.rules.table_close = function(tokens, idx, options, env, self) {
    return self.renderToken(tokens, idx, options) + `</div>`
};
```

Which allows me to add the following style:

```css
.table-wrapper {
    overflow-x: auto;
}
```

**Comment by WickyNilliams** [comment]
@KyleMit this was exactly what i was looking for, thanks!
