### ISSUE TITLE
[FG-VD-19-053] Markdown-it is vulnerable to denial of service via rendering svg file

### ISSUE THREAD

**Issue by tsug0d** [markdown-it/markdown-it#557]
## Description:
markdown-it is vulnerable to Denial Of Service by billion laughs attack via rendering svg file
Tracking Case #: FG-VD-19-053

Fortinet's FortiGuard Labs have discovered a security issue in your markdown-it product. We estimate its risk to 3, on a scale of 1 (lowest) to 5 (highest), in terms of its impact. Please advise of the appropriate contact person in your company to handle this issue.

## Payload:
1. SVG file: view-source:https://tsug0d.com/payload/dos.svg
2. Markdown syntax vulnerable:

```
[![IMAGE ALT TEXT HERE](https://tsug0d.com/payload/dos.svg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)
```

## Server Setup Information:
Tested in https://markdown-it.github.io/

Many vendor who use markdown-it is vulnerable to this bug

**Comment by puzrin** [comment]
Could you explain, why you desided this problem is specific to markdown-it. Such linked image can be created anywhere - at forums with bbcode, for example (because visible extension does not change anything). Looks more like browser bug.

**Comment by tsug0d** [comment]
the root-cause is from malicious svg file parsed by browser, the issue is raised from 2012? I'm not sure, https://bugs.webkit.org/show_bug.cgi?id=99942
And look like it will never be fixed from browser base.

In fact, single malicious svg file won't harm anyone because it is not render. In the chain, markdown-it render it, so it is triggered and suffer from DoS attack. 

I've tested with markdown in Slack and it is not rendered, so i think there is a way to mitigation it from you.

**Comment by puzrin** [comment]
I'd like point your attention to fact, that this will happen in ANY system, allowing to insert images. Because it's very easy to create server, returning this content & svg mime for ANY extension. At markdown-it level we have no possibility to analyse this. Filtering `.svg` is kludge, because will not help 100%. We can control html markup only, and markup is NOT buggy.

Please, post it to tracker as "all image-posted sites affected". I guess it worth posting to FireFox tracker too. If FF team fix it - you could push as "this already fixed in FF"

This is NOT markdown-it bug.
