### ISSUE TITLE
Asterisk escaping in (relative or absolute) URLs doesn't work

### ISSUE THREAD

**Issue by haqer1** [markdown-it/markdown-it#608]
**E.g.:**
<pre>
var s83 = "Essai 57 : asterisk within a URL is not encoded, example/some/**/\*search-phrase\*. 37e ***chose importante***."
var s83 = "Essai 57 : asterisk within a URL is not encoded, http://example/some/**/\*search-phrase\*. 37e ***chose importante***."
var md = window.markdownit();
md.render(s83);
</pre>

**Result**: _search-phrase_

**Expected:** in CM reference impl, for instance, these escapes work, & search-phrase is surrounded by asterisks & not emphasized.

**Comment by puzrin** [comment]
That's expected behaviour for autolinks extension, not related to commonmark. If you need correct work for such case - use explicit markup as in spec. See previous closed issues with explanations.

PS. Please, use online demos for examples, when possible, as said in issue template.

**Comment by haqer1** [comment]
Just for the record, from the PoV of the considerations raised in the OP, commonmark.js works better (\ escaping as expected).

P.S. While markdown-it is slightly smaller in size, which some could consider as an advantage.

**Comment by puzrin** [comment]
This compare us not relevant, because commonmark.js does NOT supports linkification (where this problem exists in md-it). If you think different - please provide samples via online demos (markdown-it and dingus).

Those package have completely different targets. While commonmark,js provides rigid reference implementation, markdown-it provides spec implementation + flexibility (extendability). In this scope size means nothing.
