### ISSUE TITLE
Smart quotes not treated properly?

### ISSUE THREAD

**Issue by loveencounterflow** [markdown-it/markdown-it#61]
when i try to use quotes like this:

```coffee
md = """
'single'

"double"

'"double in single"'

"'single in double'"

"""
settings =
  typographer:  true
  quotes:       """«»()"""
MarkdownIt  = require 'markdown-it'
parser      = new MarkdownIt settings
console.log parser.render md
```
the result looks like this:
```html
  <p>(single)</p>
  <p>«double»</p>
  <p>(&quot;double in single&quot;)</p>
  <p>«’single in double’»</p>
```

(Note that i used these specific replacements only in order to get a clearly discernible output).

i think this is problematic on more than one count. 

First, how quotes are translated seems to be depending on whether they're enclosed in another pair of quotes. If there is any argument *for* this kind of behavior, it should be configurable.

Next, replacing a `"` in the source by a `&quot` entity (i.e. U+0022) may make sense in the context of an HTML attribute; in the context of an HTML text node, it's clutter. 

Also, single quotes within double quotes *do* get replaced—but not by what was configured; rather, `’` characters (Right Single Quotation Marks, U+2019) appear in the target text. This may be justified by saying that some ASCII single quotes cannot be unambiguously interpreted as either opening or closing, and, hence, should be read as an apostrophe. Then again, the [typogr](https://github.com/ekalinin/typogr.js) module appears to get these cases right.

(As an aside, the configuration format—a single string with four characters (codepoints?)—is quite limiting and the documentation not very clear: "when typographer enabled, and smartquotes on"—where do i have to turn smartquotes on?).

**Comment by puzrin** [comment]
I'd prefer js example + demo permalink.

At first glance things you describe are ok. Smartquotes are matched by pairs, and sequence is important escaping is done because HTML require it. Logic is here https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/smartquotes.js and it doen't make escaping itself.

About configurable options - i'm against cluttering API. Idea is to keep options count minimal, and move everything else to plugins.

**Comment by puzrin** [comment]
@loveencounterflow , please create a demo permalink with examples, it will be more easy to understand.

```
- input1
- `expected1

- input2
- `expected2`

...
```

If smartquotes have problem in logic, those will be fixed.

**Comment by loveencounterflow** [comment]
care to explain what you mean by "demo permalink"? I looked at https://markdown-it.github.io/, but i don't get it to work.

**Comment by puzrin** [comment]
1. Open https://markdown-it.github.io/ (it works, at least in my FF, just checked)
2. Type your exa,ple text
3. Copy URL of small permalink tav above text area.

If something doesn't work - let me know.

**Comment by puzrin** [comment]
I've patched CLI script with `«»()` quotes option, end executed this example:

```
'single'

"double"

'"double in single"'

"'single in double'"
```

Output is:

```
<p>(single)</p>
<p>«double»</p>
<p>(&quot;double in single&quot;)</p>
<p>«’single in double’»</p>
```

We have test for nested quotes https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/markdown-it/smartquotes.txt .

As far as i see, in current example, difference is coused by improper detection of opening/closing pair. 

- nested pairs are not processed
- the rest of single quotes are interpreted as apostrophes (looks like mistake)

May be, we could use the same logic as for emphasis. Tough, it will fail in case of nested markup, because it's hard to ignore such case as "opening":

```
<b>foo</b>"bar
```

**Comment by puzrin** [comment]
Fixed in https://github.com/markdown-it/markdown-it/commit/552c130b21b2c731a597b00b17d4db045c1099ec

**Comment by srdawes** [comment]
This markdown text gives a 500 : Internal Server Error
nbconvert failed: PDF creating failed

on trying to Download from an IPython Notebook as PDF via LaTeX:

Any old text `'Some text'` some more text.

Converting it to LaTeX and adding \usepackage{textcomp} fixes it as suggested at https://github.com/ipython/ipython/issues/7793 but it's tortuous having to do that every time.
