### ISSUE TITLE
markdown-it doesn't seem to be able to generate XHTML

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [markdown-it/markdown-it#63]
Generating XHTML is a very important feature for those of us who process the output with XSLT.
Could it be implemented?

```
$ echo '![title](img.png)' | node_modules/markdown-it/bin/markdown-it.js 
<p><img src="img.png" alt="title"></p>
```

expected

```
$ echo '![title](img.png)' | multimarkdown
<figure>
<img src="img.png" alt="title" />
<figcaption>title</figcaption></figure>
```

**Comment by Alexey-Yakovenko** [comment]
Nevermind, I found that it can do this, just not exposed via cmdline option.
Makes sense to fix the hardcoded value.

**Comment by puzrin** [comment]
Do you have use case for that? We had no plans to make full CLI alternatives to API, and existing support is very basic.

**Comment by Alexey-Yakovenko** [comment]
Yeah, we have documentation in markdown for a large project, and a set of perl scripts which use multimarkdown to process md->xhtml->xslt->final_html.

I just added markdown-it as optional markdown processor into our build system, to try it out and see how is performance and correctness. It actually works surprisingly well on such a large dataset. Just a bit slow.

It's no problem for me to patch one line in the js file. But is annoying to do it every time.
Can make a patch if you're interested.

**Comment by puzrin** [comment]
I'd like to understand general needs to avoid endless requests "one more option pleeeze". For example, to load/configure plugins.

If you need minimal markup without strikes and tables, reference implementation should be ok for you. Did you tried https://github.com/jgm/cmark? It has much better support for CLI. Also it's faster, because JS has noticeable warm-up time.

This package is targeted to be node/browser lib, producing html5 - not standalone utility. But if you are absolutely sure, that you need it and need it to run with CLI - let me know.

**Comment by Alexey-Yakovenko** [comment]
Didn't hear about cmark before now, thanks for the info -- will def try it out.
I actually tried markdown-it just out of curiosity.

As I said above, it's no problem with not adding this cmdline option. It's ok with me if you just close and forget this ticket :)

**Comment by puzrin** [comment]
Ok. Closing, until you are sure that you need it. Then just open a new ticket.

For info - `markdown-it` is advanced JS implementation of CommonMark, focused on web & syntax extendability. If it's not your goal - look reference implementations first. Those are available for many languages. That's a point to start from http://commonmark.org/
