### ISSUE TITLE
Support for Right-to-Left (RTL) languages

### ISSUE THREAD

**Issue by nezartarbin** [markdown-it/markdown-it#635]
Currently, right-to-left (RTL) languages do not show correctly. They align left-to-right (LTR). This is more of a problem when a line is written with a RTL language, but has one or few LTR language words, making it extremely difficult to read.

**Comment by puzrin** [comment]
1. Direction is NOT related to markdown anyhow. Required CSS properties can be set on outer blocks.
2. All requests about syntax extension should be done at commonmark forum, as said in issue template. https://talk.commonmark.org/t/explicit-rtl-indication-in-pure-markdown/286

**Comment by iMrDJAi** [comment]
Just use this css class: `unicode-bidi: plaintext;`.
The only negative point is it's not supported on ms edge browser.

**Comment by ahangarha** [comment]
> Just use this css class: `unicode-bidi: plaintext;`.

This is not the solution. it brings some complexities and in cases (like for ol/ul) it doesn't work properly.

Gitlab for a long time has implemented bidi (bidirectional) support by adding `dir="auto"`. Github also has added this feature weeks ago.

I would request to open this issue again.

**Comment by iMrDJAi** [comment]
> > Just use this css class: `unicode-bidi: plaintext;`.
> 
> This is not the solution. it brings some complexities and in cases (like for ol/ul) it doesn't work properly.
> 
> Gitlab for a long time has implemented bidi (bidirectional) support by adding `dir="auto"`. Github also has added this feature weeks ago.
> 
> I would request to open this issue again.

@ahangarha I confirm, `unicode-bidi: plaintext;` was just half of the solution.

**Comment by puzrin** [comment]
> I would request to open this issue again.

@ahangarha do you have any concrete proposal? I still don't understand how bidi request can be related to this package.

**Comment by ahangarha** [comment]
I request @puzrin to reopen this issue so we can discuss to find best solution.

One `marked` project, they decided to make a plugin for it which can be found here: https://github.com/markedjs/marked-bidi. Maybe this can be also the solution here. So the main repo remain intact but we have a plugin which can be used. If after a year there be no negative report, then maybe it can be considered to merge and use a config entry to switch on/off the feature.

**Comment by puzrin** [comment]
> Gitlab and Github use the same method of adding `dir="auto"` to almost all elements. There are more into it but we can discuss if you are open to it.

Nobody prohibit to discuss anything in closed issues too, and create new one when required.

The first question is why do you ask for mainsteam changes. You can create plugin, which scans block tokens and and push `['dir', 'auto']` everywhere. That's should not be difficult. Mainstream changes are usually considered when creating of plugin is impossible.

**Comment by iMrDJAi** [comment]
> > Gitlab and Github use the same method of adding `dir="auto"` to almost all elements. There are more into it but we can discuss if you are open to it.
> 
> Nobody prohibit to discuss anything in closed issues too, and create new one when required.
> 
> The first question is why do you ask for mainsteam changes. You can create plugin, which scans block tokens and and push `['dir', 'auto']` everywhere. That's should not be difficult. Mainstream changes are usually considered when creating of plugin is impossible.

@puzrin Probably a plugin is enough, but I think more software should consider supporting RTL internally. We (RTL languages speakers) always face a bad user experience due to the lack of RTL support.

I'm ready to help you to do that anyway, you should give it a shot.

**Comment by puzrin** [comment]
@iMrDJAi the default policy is "everything, doable via plugins should be rejected, to keep api clean". As you can see, we have many extra repos in this org, for very popular demands. I see nothing special in bidi request, why it should bypass default policy.

I'd suggest you to create & publish new plugin.

**Comment by ahangarha** [comment]
@iMrDJAi The issue is CommonMark which is one of the most important sources for Markdown standards is not responsive. I try to follow up with them and simply because after more than 2 years, I am still a new user for them, I cannot post anything extra in their Discourse.

I can understand why projects like Markdown-it would prefer to keep their main repo following the exact same standards. That is fine for me.

@puzrin 
And I think it is a good solution to make a plugin. I need to study more the documentation and see how to make such plugin for this package. I am yet not very good in JS so if there be any help, it is very much appreciated.

**Comment by iMrDJAi** [comment]
> @iMrDJAi the default policy is "everything, doable via plugins should be rejected, to keep api clean". As you can see, we have many extra repos in this org, for very popular demands. I see nothing special in bidi request, why it should bypass default policy.
> 
> I'd suggest you to create & publish new plugin.

@puzrin I understand. I'm ok with a plugin as long as its repo will belong to the `markdown-it` organization, and not a non-official third-party one. I'd consider that as an official RTL support.

@iMrDJAi RTL isn't something that CommonMark should put a standard for, it's already a standard by itself but unfortunately people forget/are too lazy to follow it.

**Comment by puzrin** [comment]
@iMrDJAi i think we spend too much time for talks about trivial plugin. And i don't sell/rent/donate place in this org. As i said before, i see absolutely no reason to apply custom approach for such [ordinary] plugin. People who need it could just do it..

**Comment by ahangarha** [comment]
> RTL isn't something that CommonMark should put a standard for, it's already a standard by itself but unfortunately people forget/are too lazy to follow it.

Not sure about this. In many projects, Markdowd to HTML parser should works based on CommonMark specification. At least this is what I am told. And it make sense. If everyone decide to part it in a different way, then how we can rely on parsers. Some minor changes are fine but the overall result should follow the same logic.

Since my proposal (same as Gitgub and Gitlab approach) needs few modification in HTML (though it is not destructive at all the current status of LTR contents) then they are right if they resist against breaking standards.

Instead, I suggest us to make more and more examples for bidi support implementation. I have done in multiple cases and keep working more. Even if there be an unofficial plugin, it is fine. If it work, it might merge with the main project in future. For that we need to push CommonMark. It makes absolute sense that changing a standard be a time consuming procedure. Otherwise calling it standard makes no sense.

So let's play our rule the best and hope in near future, bidi support be officially added to CommonMark. It took more that 5 years t convince Github to add bidi support.

**Comment by ahangarha** [comment]
@puzrin I respect time and energy you have put in such projects. More, I appreciate your participation in this conversation. I think we are on right track.

**Comment by iMrDJAi** [comment]
> And i don't sell/rent/donate place in this org

@puzrin Well, that's not what I meant.

> i think we spend too much time for talks about trivial plugin

Honestly, I don't care whether the library itself supports RTL or not. My goal is to make developers aware of the fact that RTL isn't "trivial". It's indeed an obligation and not something optional.

**Comment by puzrin** [comment]
IMO mentoring in this tracker is not good idea, sorry. It things can be done via plugins, i see no reasons to spend my personal time for those.

**Comment by iMrDJAi** [comment]
@ahangarha I am sure 100% that other standards have nothing to do with RTL. It's something that should be supported initially, It should be present wherever UTF-8 characters are rendered.

The problem is developers are just ignoring that fact. What if the Latin alphabets are written right to left instead (that was a thing at some point in history btw)? In this case, RTL is what we initially use and not LTR. Just think about it.

**Comment by ahangarha** [comment]
@iMrDJAi Frankly, implementing RTL or actually bidi support is very easy and maybe one can say "trivial". Just look at [marked-bidi](https://github.com/markedjs/marked-bidi) plugin. If we know how to use Markdown-it API, rest is easy.

The issue is nobody among RTL people helps with implementation. I would love to sit and collaborate with someone who know more than me to read the documentation and understand what to do. Let's don't push more here. If you think we can work together on this, I am already in. Let's discuss that somewhere else (matrix, telegram, email, irc).

**Comment by iMrDJAi** [comment]
@ahangarha Interested, you can reach me out on telegram (username is the same as my Github's).

@puzrin BTW you did nothing wrong. I really appreciate your work and your contribution to open-source. These changes aren't supposed to be made in the first place if browsers support RTL out of the box. (I should blame the deveploers behind browsers instead xD)

**Comment by ahangarha** [comment]
I just wanted to inform that me and @iMrDJAi are working on plugin for adding bidi support and we have aleady made good progress (v0.0.2 at the moment). If interested, check the npm and github page here:

https://www.npmjs.com/package/markdown-it-bidi

https://github.com/ahangarha/markdown-it-bidi

Eager to get feedback for improvement. We need to make sure this plugin has no issue to be integrated with markdown-it and other plugins.

**Comment by iMrDJAi** [comment]
Also, I'm willing to propose changes to the CommonMark specs regarding bidirectional text support. The proposal should be as detailed as possible, and concrete enough so it will be easy for them to adopt it.

@ahangarha We should continue working on it. We still have a lot to do!

**Comment by ahangarha** [comment]
Sure we have a lot to do. We will follow our long to-do-list separately and hopefully this plugin can help more projects add bidi support so we get more feedback and finally CommonMark improve their standards with more confidence.
