### ISSUE TITLE
Link render problem

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [markdown-it/markdown-it#661]
the link is not rendered properly in markdown-it, for some reason, it gets truncated

URL:

https://ourworldindata.org/grapher/covid-deaths-days-since-per-million?zoomToSelection=true&time=9..&country=FRA+DEU+ITA+ESP+GBR+USA+CAN

Rendered link goes to:

https://ourworldindata.org/grapher/covid-deaths-days-since-per-million?zoomToSelection=true&time=9

![image](https://user-images.githubusercontent.com/54576074/79461968-835f8d00-8014-11ea-8da3-03989846c677.png)
---
![image](https://user-images.githubusercontent.com/54576074/79461971-8490ba00-8014-11ea-8466-006e569365e6.png)

**Comment by axq** [comment]
This is somehow very specific to where the double period occurs in the URL.

Renders fine:
https://ourworldindata.org/grapher/total-deaths-covid-19?yScale=log&time=34..68&country=BRA+FRA+DEU+ITA+NLD+SGP+ESP+TWN+GBR+USA+CZE

Truncated:
https://ourworldindata.org/grapher/covid-deaths-days-since-per-million?yScale=linear&zoomToSelection=true&time=2020-01-30..&country=CAN+FRA+DEU+ITA+ESP+GBR+USA+SWE+TWN+KOR
(becomes https://ourworldindata.org/grapher/covid-deaths-days-since-per-million?yScale=linear&zoomToSelection=true&time=2020-01-30)

**Comment by Rahulm2310** [comment]
@axq Links with double period just before **&** are truncated

**Comment by laurent22** [comment]
That looks like the ".." is filtered out, perhaps for security reason, but in this particular case it's not necessary.

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L59

There are strict limits in linkifier to avoid false positives. Just need one more exclusion. Thanks for reporting.

**Question.** Example has `leters..&` sequence. Does `&..leters` need fix too or not? Any samples?

**Comment by Rahulm2310** [comment]
No, `&..letters` is rendering perfectly. The problem only exists with `..&letters`

**Comment by puzrin** [comment]
Thanks. If that's not extremely urgent, i'll fix in 1-2 weeks with other things.

**Comment by puzrin** [comment]
Released 11.0.0
