### ISSUE TITLE
Inline token renders to empty tag

### ISSUE THREAD

**Issue by sverona** [markdown-it/markdown-it#801]
I'm working on a plugin that essentially renders sidenotes/footnotes within paragraphs. I thought I understood the rule/chain model, but I have been proven wrong.

Specifically, I have a rule that turns this structure:

```json
Token { type: "inline", children:
[ 
    Token { type: "text" },
    Token { type: "sidenote_ref" },
    Token { type: "text" }
]
}
```

into this structure:

```json
Token { type: "inline", children:
[ 
    Token { type: "text" },
    Token { type: "sidenote_ref" },
    Token { type: "sidenote_open" },
    Token { type: "paragraph_open" },
    Token { type: "inline", children: [...] },
    Token { type: "paragraph_close" },
    Token { type: "sidenote_close" },
    Token { type: "text" }
]
}
```
(I've stripped out most of the attributes for brevity.)

The `sidenote_open` and `sidenote_close` tokens render as expected, but the `inline` in between them renders to an empty tag. For instance, this Markdown:

```md
Here is a paragraph.^[Here is a sidenote.] Here is some more text after the sidenote.
```

renders to this HTML:

```html
'<p>Here is a paragraph.<label aria-describedby="fn1" role="presentation" class="sidelink" for="fn1-content">\n' +
  '<a aria-hidden="true" href="#fn1"><output class="highlight fnref" id="fnref1">[1]\n' +
  '</output></a></label><aside id="fn1" class="sidenote" role="note">\n' +
  '    <output aria-hidden="true" class="highlight" id="fn1-content">\n' +
  '    <label role="presentation" for="fnref1"><p><> <a href="#fnref1" class="sidenote-backref">↩︎</a></p>\n' +
  '</label></output></aside>\n' +
  ' Here is some more text after the sidenote.</p>\n'
```

I have checked the documentation and the codebase and am uncertain why this token does not render. My best guess is that there is no rule to parse an `inline` token that is itself inside an `inline` token, because this is AFAICT impossible to write in CommonMark. Am I remotely correct? If so, what's the most appropriate way to structure the token stream so that this token renders?

**Comment by rlidwka** [comment]
> My best guess is that there is no rule to parse an inline token that is itself inside an inline token

Yes.

CommonMark spec doesn't define any of this, but it defines two levels of parsing (block tokens and inline tokens). So we represent them as 2d array (array of block tokens on top, which may contain `inline` with array of inline tokens inside).

So the answer is: don't put `inline` inside `inline`, instead you should flatten inner one.

Instead of this:

```js
Token {
  type: "inline", children: [
    Token { type: "text" },
    Token { type: "inline", children: [
      Token { type: "text" },
      Token { type: "text" }
    ] },
    Token { type: "text" }
  ]
}
```

generate this:

```js
Token {
  type: "inline", children: [
    Token { type: "text" },
    Token { type: "text" },
    Token { type: "text" }
    Token { type: "text" }
  ]
}
```

Pretty sure code to do this is trivial, and everything should render then.

*Note: you may run into issues displaying it in a browser correctly, since nested `<p>` tags aren't allowed in HTML as far as I remember. So better approach would probably be to flatten top level, replacing <p> with <div>, but that's no longer markdown problem.*

**Comment by sverona** [comment]
Works great! Thank you <3
