### ISSUE TITLE
Documentation for token names

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [markdown-it/markdown-it#822]
I haven't been able to find a list of token names that markdown-it uses to map to native DOM elements. If there isn't already a list of token names somewhere, could one be added? Lack of documentation for this makes it difficult to customize plugins that rely on custom rendering logic. e.g., see this comment: https://github.com/HiroshiOkada/markdown-it-class/pull/3#issuecomment-717652979

**Comment by rlidwka** [comment]
> I haven't been able to find a list of token names that markdown-it uses to map to native DOM elements.

`markdown-it` does not map token names to native DOM elements. It uses other properties of a `token` object (for example, DOM element tagName is generated using `token.tag`).

Token names are used by end users to customize specific tags, in which case you would already know which tags you want to customize. Thus, there's no need for a list. *It's worth pointing out that a full list of token names is impossible to make since every plugin can add their own token types.*

I can't imagine a use-case when plugins would need to use token names, for example in markdown-it-class `token.nesting` property should be a better option (I commented on it there).
