### ISSUE TITLE
Unexpected treatment of HTML based on writing it inline or hierarchically indented

### ISSUE THREAD

**Issue by alanfluff** [markdown-it/markdown-it#860]
**Aside:** mods, please feel free to close this or mark it as something other than a bug it that seems right, thanks, and sorry if I misfiled or missed something in the docs.

<hr>

This written in a Markdown document (because I want to write some raw HTML for Markdown to ignore and the browser to render):
```
<a class="dogs" href="#99">
	<p class="cats">
		mice
	</p>
</a>
```
gets rendered as:
```
<a class="dogs" href="#99">
	<p class="cats">
		mice
	</p>
</a>
```
Just what I expected.

And yet write the same HTML in the Markdown doc like *this*:
```
<a class="dogs" href="#99"> <p class="cats"> mice </p> </a>
```
and it gets rendered as this:
```
<p class="cats">
	<a class="dogs" href="#99">
		mice
	</a>
</p>
```
`cats` and `dogs` are swapped.

I assume this is a side effect of the sort of issue [noted in item 3 here](https://stackoverflow.blog/2008/06/25/three-markdown-gotcha/).

Are there any clear rules for mixing HTML in when it comes to markdown-it (i.e always write hierarchically indented and it will work as expected)?

I hope this helps anyone else who has been confused by this behaviour.

Thanks for any comments.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ca%20class%3D%5C%22dogs%5C%22%20href%3D%5C%22%2399%5C%22%3E%20%3Cp%20class%3D%5C%22cats%5C%22%3E%20mice%20%3C%2Fp%3E%20%3C%2Fa%3E%5Cn%5Cntest%5Cn%5Cn%3Cdiv%20class%3D%5C%22dogs%5C%22%3E%20%3Cp%20class%3D%5C%22cats%5C%22%3E%20mice%20%3C%2Fp%3E%20%3C%2Fdiv%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

extra `<p>` happens, because `<a>` is inline tag. `<div>` does not add `<p>`. All that logic is described in commonmark spec. It's better use https://talk.commonmark.org/ or SO for such questions. This repo is not about commonmark in general, but about concrete implementation.

**Comment by alanfluff** [comment]
Thanks very much @puzrin. It is helpful and reassuring to understand where this apparent anomaly comes from.

I *will* comment there since this "rule" seems somewhat out of step now (since HTML5) given the spec no longer imposes / defines block or inline on elements.

> [block and inline elements are no longer defined in HTML 5](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#list_of_inline_elements)

Cheers!
