### ISSUE TITLE
ES Module (ESM) build in the npm package

### ISSUE THREAD

**Issue by paulirwin** [markdown-it/markdown-it#862]
Like #852 but for the npm package version, as I do not use the jsDelivr build. (I have a transitive npm dependency on markdown-it via prosemirror-markdown.)

When trying to use this library in an Angular application, we get the following compiler warning:
```
Warning: [redacted_file_path] depends on 'markdown-it/lib'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

It is now commonly recommended to support ES Module (ESM) builds in addition to legacy formats, which also has the added benefit of better bundle optimization. All supported versions of Node.js at the time of this writing fully support ES Modules, with the exception of Node 12 which has it behind an experimental flag, but that version is going out of support at the end of this month (April 2022).

The UMD/CommonJS build can be retained for those users that need it, but having an ESM build in addition to the UMD build would be ideal.

I'd be happy to take a stab at this, unless one of the core team members would prefer to do it. Thanks!

**Comment by kintz09** [comment]
With CRA no longer being recommended by React, I'm aiming to switch to Vite. This is one of the packages causing problems because it doesn't offer ESM import support. I see there's a PR (#862) out from April that may resolve that issue but after reading through some issues in the repo I'm a little confused as to whether or not this package will be updated to support ESM.

Could anyone help clarify?

**Comment by puzrin** [comment]
Solved in master.

**Comment by u12206050** [comment]
Solved but not published?
