### ISSUE TITLE
Render reference links

### ISSUE THREAD

**Issue by webdiscus** [markdown-it/markdown-it#875]
Thank You for your great work!

Currently, reference link in not rendered.

```md
[reference](1)

[1]: https://google.com
```
Expected:
```html
<a href="https://google.com">reference</a>
```

But the result:
```html
<a href="1">reference</a>
```

Here is the [link to demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Breference%5D%281%29%20%7C%20%5Blink%5D%28http%3A%2F%2Fdev.nodeca.com%29%5Cn%5Cn%5B1%5D%3A%20http%3A%2F%2Fdev.nodeca.com%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Atrue%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) on https://markdown-it.github.io.

It would be nice to have this feature, like it work on GitHub.

**Comment by puzrin** [comment]
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Bfoo%5D%5Cn%5Cn%5Bfoo%5D%3A%20https%3A%2F%2Fgoogle.com%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

You used wrong markup. See https://spec.commonmark.org/0.30/#link-reference-definition

Be sure to check in https://spec.commonmark.org/dingus/ if you report deviation from spec.

**Comment by zimeg** [comment]
Faced similar strangeness due to incorrect markdown formatting:

```md
this is an [example post][example].

<!-- links -->
[example]: https://example.com
```

Using either [HTML mode](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22this%20is%20an%20%5Bexample%20post%5D%5Bexample%5D.%5Cn%5Cn%3C!--%20links%20--%3E%5Cn%5Cn%5Bexample%5D%3A%20https%3A%2F%2Fexample.com%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) or adding a line break before the comment and removing the comment fixes this!
