### ISSUE TITLE
Add option to disable trimming table cell content

### ISSUE THREAD

**Issue by susnux** [markdown-it/markdown-it#904]
Sometimes I want to get the raw table cell string rather than the trimmed one, e.g. because I want to serialize it back to md without changing it.
So it would be nice if an option is added to disable the `trim` on the table cell content.

e.g. currently this:
```
| hello |    world |
```
is parsed to:
```html
<td>hello</td><td>world</td>
```

where I would like to have:
```html
<td>hello</td><td>   world</td>
```

(Even though I used HTML it would be ok to just have the whitespaces untouched within the tokenized version)

**Comment by puzrin** [comment]
Sorry, the project policy is to use plugins instead of adding new options in the mainstream. There are many demands about tables, but we implement only a minimal feature set, as on github, until this is updated in commonmark spec.

**Comment by susnux** [comment]
@puzrin but how should this be done? It would require to copy the whole table parsing just to remove the trim.
Otherway around I would understand, but with having the trim in core there is nothing a plugin can do.

**Comment by puzrin** [comment]
Yes, you need to create your code for the table or search existing plugins, probably those could support the behavior you need.

> but with having the trim in core there is nothing a plugin can do.

There are hundreds of such requests, and accepting those into the core will mess up API very quickly. That's why we support only spec things and the minimal possible set of de-facto standards like strikethrough & table from github.
