### ISSUE TITLE
markdown-it with mermaid

### ISSUE THREAD

**Issue by personalsoft-fabianobonin** [markdown-it/markdown-it#929]
Hello,

I'm having trouble integrating Mermaid into Markdown-it. Although there are several plugins available, none of them seem to work for me.

I was wondering if anyone has successfully used Mermaid with Markdown-it and could share some instructions on how to set it up.

Thanks in advance,
Fabiano

**Comment by sebastianwessel** [comment]
@personalsoft-fabianobonin 
Had the same issue, but was able to solve it by simply not using plugins:

```typescript
import 'highlight.js/styles/atom-one-dark.css'
import  'mermaid'

import hljs from 'highlight.js'
import MarkdownIt from "markdown-it";

const renderer = new MarkdownIt({
  linkify: true,
  typographer: true,
  highlight: function (str, lang) {
    if(!lang) {
      return ''
    }
    if (hljs.getLanguage(lang)) {
      try {
        return '<pre><code class="hljs">' +
          hljs.highlight(str, { language: lang, ignoreIllegals: true }).value +
          '</code></pre>';
      } catch (__) { }
    }
    if(lang.toLowerCase()==='mermaid') {
       return '<pre class="mermaid">'+str+'</pre>'
    }
    
    return '';
  }
});
```

This renders the mermaid for me.
If you're using something like vue, react or similar, you might need to call `mermaid.contentLoaded()` because mermaid runs only on first page load

Hope, this helps 🤞
