### ISSUE TITLE
Invalid HTML produced when using <pre> tag in html mode

### ISSUE THREAD

**Issue by pilotmoon** [markdown-it/markdown-it#951]
When `<pre>` is used in the input in a certain way, and html mode is on, then markdown-it can produce invalid HTML output:

[Demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ch1%3EHeading%3C%2Fh1%3E%5Cn%3Cpre%3E%5CnFirst%20line%20of%20text%5Cn%5CnSecond%20line%20of%20text%5Cn%3C%2Fpre%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

Input:
```
<h1>Heading</h1>
<pre>
First line of text

Second line of text
</pre>
```

Output:
```
<h1>Heading</h1>
<pre>
First line of text
<p>Second line of text
</pre></p>
```

(Note that the `<p>` tag is erroneously inserted around second line of text and then `</pre>` is inserted before closing `</p>` tag, violating nesting rule.)

I checked and I noted that GitHub's markdown implementation [handles the same input OK](https://gist.github.com/pilotmoon/1aee949c5c0399927d4187d5bb3fb583) .

**Comment by kliu57** [comment]
I would like to work on this.

**Comment by kliu57** [comment]
@puzrin @pilotmoon 

I looked into this issue, and I found that although this behavior does not match the GitHub implementation, this is actually **expected behavior** according to [commonmark specs](https://spec.commonmark.org/0.30/#html-blocks).

![commonmark specs](https://github.com/markdown-it/markdown-it/assets/98062538/d27a38d8-bf8a-4aef-a2c4-266cda256ab9)

However, if you wish for the code to not follow the commonmark specs behavior, I have a **proposed fix**:

Add `pre` to the list of valid html block names in `lib/common/html_blocks.js`, and the result will then match the GitHub implementation behavior. I have tested this and can provide screenshots of results.

Please let me know what behavior is desired.

**Comment by puzrin** [comment]
As written above - works as spec says. Details about spec desitions can be seen on commonmark forum.
