### ISSUE TITLE
Support GFM Notes 

### ISSUE THREAD

**Issue by calumk** [markdown-it/markdown-it#974]
I dont know if this would be best as a plugin or native

GFM allow for markup such as : 

> [!IMPORTANT]
> This is an important note

> [!WARNING]
> This is a warning

https://github.com/orgs/community/discussions/16925 

It is not the same format used by the containers plugin : https://mdit-plugins.github.io/container.html

**Comment by rlidwka** [comment]
This is absolutely a plugin.

`markdown-it` supports commonmark standard only at this point. There are a few inconsistencies between it and gfm, because of which we don't want to get into business of supporting that (gfm wasn't even a standard last I checked).

I think gfm is being implemented as a plugin by other people, maybe ask there.

> [!NOTE]  
> oh that's a cool feature, didn't know it existed
> not sure if it's gonna make github issues better or worse if people are going to spam it

**Comment by calumk** [comment]
If it will be best suited as a plugin, I will referenced by other issues, and I will close this
